### ISSUE TITLE
Argon2 hashing

### ISSUE THREAD

**Issue by ximuh** [jedisct1/libsodium-php#101]
hi everyone, not sure where to post this as not many people know about argon2 and libsodium on stackoverflow. i am using this guide: https://paragonie.com/blog/2016/02/how-safely-store-password-in-2016

here is the code im talking about:

```
$hash_str = \Sodium\crypto_pwhash_str(
    $password,
    \Sodium\CRYPTO_PWHASH_OPSLIMIT_INTERACTIVE,
    \Sodium\CRYPTO_PWHASH_MEMLIMIT_INTERACTIVE
);
```

after i hash the password, it shows up like this:

`$argon2i$v=19$m=32768,t=4,p=1$C6A02mjK0DA1TmmpwKx14A$3/KZUJvLaKtW0V0uh/gfhHN3oaS....`(trimmed the last parts off)

i see it starts with $argon2i$... is that normal? am i doing everything right?

**Comment by paragonie-scott** [comment]
Yep. That's the sort of result we'd expect. To test it:

    var_dump(\Sodium\crypto_pwhash_str_verify($hash_str, $password));

If you get `bool(true)` with the correct password and `bool(false)` with an incorrect password, all is right in the world.

Also, as the author of the relevant blog post, I'll add some example hash outputs to the article in my next update.

**Comment by ximuh** [comment]
@paragonie-scott Awesome.. thank you so much!
