### ISSUE TITLE
Proposal: Don't build against libsodium < 1.0.9

### ISSUE THREAD

**Issue by paragonie-scott** [jedisct1/libsodium-php#102]
Linux packages continue to provide 1.0.3 or 1.0.8 despite 1.0.11 being released. In a future version, I'd like to propose blocking the PHP extension from compiling against older versions unless the user passes a specific string argument to the `pecl install` command.

For example: `--allow-outdated`

(Feel free to reject if there's a better solution available to us, of course.)

**Comment by jedisct1** [comment]
Debian-stable is even worse here, since it's still shipping version 1.0.0 :(

Requiring a specific argument is a good idea. I'm not sure how to do that with `pecl` and if this is possible at all, but I'll take a look.

**Comment by jedisct1** [comment]
Distributions with old packages (and/or people running outdated distros) are annoying. I hate having to support these old things as well.

That being said, it should be as easy as possible to install the extension. Including for people who can't /don't want to/don't know how to install a recent version of the library.

If it doesn't work out of the box, many people will just give up and use something else.

I'd suggest still supporting these old versions, without having to pass a specific `configure` flag, but the script can still spit out warnings about the version being old.
And stop supporting these old versions right after the next Debian stable is released.

**Comment by paragonie-scott** [comment]
Sounds like a good plan to me.
