### ISSUE TITLE
COW violation in sodium_increment

### ISSUE THREAD

**Issue by nikic** [jedisct1/libsodium-php#106]
In https://github.com/jedisct1/libsodium-php/blob/master/libsodium.c#L452 a string is modified directly, which might have rc>1 (i.e. a SEPARATE_STRING call is missing). Additionally the parameter should be accepted by reference.

**Comment by nikic** [comment]
The same problem also exists for the first argument of `sodium_add`.

**Comment by jedisct1** [comment]
You seem to be way more familiar with the PHP internals that I am :)

Would you mind submitting a pull request to fix this?

**Comment by nikic** [comment]
Sure, I'll send a PR after the drop of PHP 5 lands.
