### ISSUE TITLE
Missing returns after E_RECOVERABLE_ERROR

### ISSUE THREAD

**Issue by nikic** [jedisct1/libsodium-php#107]
The current code assumes that a bailout occurs on E_RECOVERABLE_ERROR -- however, these errors may be ignored by an error handler, in which case control will resume after the error. This will usually lead to a segfault in subsequent code.

After throwing E_RECOVERABLE_ERROR, the code should free/release any resources and return from the function. (Once #93 is implemented, doing so will be necessary in any case, not just to handle this somewhat obscure edge-case.)

**Comment by paragonie-scott** [comment]
I'm currently writing a patch for this. Converts to throwables and adds a return. Should be coming soon.

**Comment by nikic** [comment]
This one is resolved by #113 as well.
