### ISSUE TITLE
parameter count for compare method not correct

### ISSUE THREAD

**Issue by fkooman** [jedisct1/libsodium-php#108]
Hi,

I ran into an issue with using phan [1] to (statically) check my code. It turns out that libsodium-php has an issue with (at least) the `compare` function [2].

The function takes two arguments, but here it is listed as only requiring one parameter. This causes Phan to give a warning [3]:

```
sodium_test.php:3 PhanParamTooManyInternal Call with 2 arg(s) to \Sodium\compare() which only takes 1 arg(s)
```

[1] https://github.com/etsy/phan 
[2] https://github.com/jedisct1/libsodium-php/blob/f53513c499f05dbc337e03c82dcfcbe671e8649c/libsodium.c#L220
[3] https://github.com/etsy/phan/issues/513

**Comment by jedisct1** [comment]
Fixed thanks!
