### ISSUE TITLE
Call to undefined function Sodium\crypto_shorthash()

### ISSUE THREAD

**Issue by peterkahl** [jedisct1/libsodium-php#110]
I am running libsodium-php on Ubuntu and nginx. All seems to work fine until I try to execute a PHP script that uses a libsodium function from crontab.
```
Error: Call to undefined function Sodium\crypto_shorthash().....
```
I am running the crontab as user vmail, but switching to user root makes no difference.

**Comment by paragonie-scott** [comment]
Are you using dev-master? It's switched to `sodium_crypto_shorthash()` but version 2.0.0 has not been tagged yet. At minimum, I believe it's waiting on #109.

**Comment by peterkahl** [comment]
No, not dev-master.

**Comment by paragonie-scott** [comment]
Well, crypto_shorthash has been in the extension since v0.1.1 so it's unlikely that it's a version conflict.

Is `extension=libsodium.so` in the relevant php.ini file?

**Comment by peterkahl** [comment]
Yes, I have `extension=libsodium.so` in the php.ini file.

**Comment by peterkahl** [comment]
![screen shot 2017-02-23 at 06 37 13](https://cloud.githubusercontent.com/assets/2703373/23236026/a4aea326-f992-11e6-97f3-1e8e0df710da.png)

**Comment by paragonie-scott** [comment]
Is that also accessible from php-cli?

What does `php -i | grep libsodium | wc -l` produce from command line?

**Comment by peterkahl** [comment]
`0`

**Comment by paragonie-scott** [comment]
Okay, that produces `6` on my machine. Find the `php.ini` for `php-cli` and append `extension=libsodium.so` to the bottom, and it should work again.

**Comment by peterkahl** [comment]
Yup. That was it!
```
solved && verified && thanks
```

**Comment by jedisct1** [comment]
Thanks, Scott!
