### ISSUE TITLE
API change suggestion: use a state object for generichash_init/update/final

### ISSUE THREAD

**Issue by fredemmott** [jedisct1/libsodium-php#119]
At the moment, the extension copies the struct into a string. On update, it copies it if refcount is > 1. The original may or may not be securely wiped.

Using an object (wrapping the C struct) would:
 - provide better encapsulation
 - make it possible to ensure that all clones are securely wiped
 - avoid the need for the extension to care about string refcounts, which in HHVM are generally considered an implementation detail (not a blocker, just means I'm using internals to implement sodium_separate_string)

**Comment by jedisct1** [comment]
That's a good idea. Better encapsulation makes it more future-proof.

**Comment by fredemmott** [comment]
Also applies to private key data; maybe provide KeyData::fromString(), fromFile(), fromStream(), with the latter two never having the key data in a normal PHP string. AIUI this memory should also be marked with mlock()

**Comment by jedisct1** [comment]
Hi Fred,

That would have been great, but it's probably too late to change the API now :(
