### ISSUE TITLE
Nit: exception for bad seed size for crypto_box_seed_keypair_seed_size is slightly inconsistent

### ISSUE THREAD

**Issue by fredemmott** [jedisct1/libsodium-php#120]
https://github.com/jedisct1/libsodium-php/blob/master/libsodium.c#L891

> "seed should be crypto_box_SEEDBYTES long"

Most functions have the const in all caps (matching PHP), and say 'bytes' instead of 'long'

**Comment by fredemmott** [comment]
Ditto for crypto_sign_seed_keypair

**Comment by jedisct1** [comment]
Thanks Fred,

Could you possibly send pull requests for these?

**Comment by fredemmott** [comment]
hopefully - waiting for legal approval
