### ISSUE TITLE
Nit: crypto_sign_detached exception messages are inconsistent

### ISSUE THREAD

**Issue by fredemmott** [jedisct1/libsodium-php#122]
- result !=0 exception doesnt' include ": internal error"
 - bogus size exception doesn't include function name

**Comment by fredemmott** [comment]
Same for the ed25519_pk_to_curve25519 functions

**Comment by fredemmott** [comment]
sodium_crypto_stream() and _stream_xor() are intenrally inconsistent about if the exceptions include the function name

**Comment by fredemmott** [comment]
and salsa

**Comment by jedisct1** [comment]
Should be fixed in 18f7072fbf25b98beeee58e2c8f4bb345c961778 thanks!
