### ISSUE TITLE
PHPv7.2.0

### ISSUE THREAD

**Issue by peterkahl** [jedisct1/libsodium-php#128]
Can't run libsodium-php on PHPv7.2.0. Getting this error:
```
ErrorException: PHP Startup: libsodium: Unable to initialize module
Module compiled with module API=20160303
PHP    compiled with module API=20160731
These options need to match
```

**Comment by padraigdoran** [comment]
libsodium-php is due to be integrated into PHP v7.2 so I wonder if you'll be better of waiting until it is integrated. It's currently stuck on a licensing issue #127

**Comment by peterkahl** [comment]
Oops. Completely forgot about that!
Thanks.

**Comment by sgolemon** [comment]
For future reference, that error message means that you need to recompile the extension you're trying to load.  You sodium.so was compiled against 7.1.0 which has a subtly different API than 7.2.0.  Simply reissuing `phpize && ./configure && make` on it will produce a new version intended for PHP 7.2's API.

Note that 7.2 isn't final yet, and the API number is expected to change one more time in about two weeks when php-7.2.0beta1 is released.
