### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by imsaeed** [jedisct1/libsodium-php#130]
I follow everything to a tee here:
https://paragonie.com/book/pecl-libsodium/read/00-intro.md#installing-libsodium

When running the version check, I just get

root@tunnel:~/libsodium# php h.php
PHP Fatal error: Uncaught Error: Call to undefined function Sodium\library_version_major() in /root/libsodium/h.php:3
Stack trace:
#0 {main}
thrown in /root/libsodium/h.php on line 3

I am using PHP7, not sure what else to do. phpenmod did not work, manually editing the php.ini did not work, even after an apache2 restart/reload. Installed libsodium from source, tried both latest and 1.0.10 versions.  libsodium-php v 1.06

**Comment by paragonie-scott** [comment]
> phpenmod did not work, manually editing the php.ini did not work, even after an apache2 restart/reload

* Which .ini files are you updating? On many systems, you have to do it for both apache2 and cli.
* What operating system?

**Comment by imsaeed** [comment]
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial

Edited both /etc/php/7.0/apache2/php.ini and /etc/php/7.0/cli/php.ini

root@tunnel:~/libsodium# pecl install libsodium
pecl/libsodium is already installed and is the same as the released version 1.0.6
install failed
root@tunnel:~/libsodium# nano /etc/php/7.0/cli/php.ini
root@tunnel:~/libsodium# service apache2 reload
root@tunnel:~/libsodium# php h.php
PHP Fatal error:  Uncaught Error: Call to undefined function Sodium\library_version_major() in /root/libsodium/h.php:3
Stack trace:
#0 {main}
  thrown in /root/libsodium/h.php on line 3

**Comment by paragonie-scott** [comment]
Hmm, a couple more things to try:

* What is the output of `which php` and `php -v`? If you have multiple versions installed, this may explain the error.
* If you put `extension=libsodium.so` in `/etc/php/7.0/mods-available/libsodium.ini` and then run `phpenmod libsodium`, does that fix it?

**Comment by imsaeed** [comment]
root@tunnel:~/libsodium# php -v
PHP 7.0.15-0ubuntu0.16.04.4 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.15-0ubuntu0.16.04.4, Copyright (c) 1999-2017, by Zend Technologies
root@tunnel:~/libsodium# which php
/usr/bin/php
root@tunnel:~/libsodium# ^C
root@tunnel:~/libsodium# nano /etc/php/7.0/mods-available/libsodium.ini
root@tunnel:~/libsodium# phpenmod libsodium
root@tunnel:~/libsodium# service apache2 restart
root@tunnel:~/libsodium# php h.php
array(3) {
  [0]=>
  int(9)
  [1]=>
  int(4)
  [2]=>
  string(6) "1.0.12"
}
root@tunnel:~/libsodium#


It would appear pushing it to libsodium.ini worked. Thank you!
