### ISSUE TITLE
Commit "Implement sodium_crypto_kdf()" breaks compile

### ISSUE THREAD

**Issue by MaSpeng** [jedisct1/libsodium-php#132]
The new implementation: **PHP_FUNCTION(sodium_crypto_kdf_derive_from_key)** breaks compile and _pecl install libsodium xdebug_ with _php-fpm_ on _docker build_.

I got the following error from compile:

> /tmp/pear/temp/libsodium/libsodium.c: In function 'zif_sodium_crypto_kdf_derive_from_key':
/tmp/pear/temp/libsodium/libsodium.c:2899:29: error: 'crypto_kdf_blake2b_CONTEXTBYTES' 
undeclared (first use in this function)
     memcpy(ctx_padded, ctx, crypto_kdf_blake2b_CONTEXTBYTES);
                                                 ^
/tmp/pear/temp/libsodium/libsodium.c:2899:29: note: each undeclared identifier is reported only once for each function it appears in
/tmp/pear/temp/libsodium/libsodium.c:2915:50: error: 'crypto_kdf_blake2b_KEYBYTES' undeclared (first use in this function)
                                                  crypto_kdf_blake2b_KEYBYTES,
                                                  ^
Makefile:194: recipe for target 'libsodium.lo' failed
make: *** [libsodium.lo] Error 1
ERROR: `make' failed
ERROR: Service 'php-fpm' failed to build: The command '/bin/sh -c set -xe     && docker-php-ext-install         bcmath         intl         pdo_pgsql     && pecl install         libsodium         xdebug     && docker-php-ext-enable         libsodium         xdebug     && apk del .build-deps' returned a non-zero code: 1
make: *** [build:dev] Error 1

This points to Line: 2.899 in **libsodium.c**.

Please fix the mentioned implementation.

**Comment by jedisct1** [comment]
Fixed thanks!

I can't push that to PECL now. So:
Please use a recent libsodium version.
