### ISSUE TITLE
Pecl extension is versioned 2.0.1 instead of 2.0.2

### ISSUE THREAD

**Issue by petk** [jedisct1/libsodium-php#134]
Hello,

if I'm not mistaken latest [pecl libsodium version 2.0.2](https://pecl.php.net/package/libsodium) is versioned as 2.0.1.

**Comment by jedisct1** [comment]
Ignore this. Thee are no differences between 2.0.0, 2.0.1 and 2.0.2 except compilation fixes for old libsodium versions.
