### ISSUE TITLE
2.x branch

### ISSUE THREAD

**Issue by moderndeveloperllc** [jedisct1/libsodium-php#136]
Just an FYI, you may want to update the README to indicate that the new 2.x versions install the extension as sodium.so and you have switched to the root namespace and sodium_*. It took me a bit to try and figure out why my install was having issues with the "latest" version. BTW, I've [generated a PR](https://github.com/Homebrew/homebrew-php/pull/4323) for the homebrew packaging system (macOS) that accounts for all the changes.

**Comment by jedisct1** [comment]
Done, thanks!
