### ISSUE TITLE
Issues in sodium_crypto_kdf_derive_from_key

### ISSUE THREAD

**Issue by nikic** [jedisct1/libsodium-php#146]
https://github.com/jedisct1/libsodium-php/blob/4e668284deaff4243c7ef36025525f44bbeb8078/libsodium.c#L2829 => These two variables should be zend_longs, otherwise there may be stack corruption on LLP64.

Additionally there should be returns after the zend_throw_exception calls -- zend_throw_exception only sets a global variable, it does not unwind.

I also want to double check, the use of warnings in sodium_crypto_pwhash for empty passwords low ops/memlimit is intentional, right?

**Comment by jedisct1** [comment]
Ah, yes, I forgot about the existence of `zend_long`. Should be fixed with 52a82f4d7307f9e71c5b50283940126687144d20 and 2aedfb8e0163b75500a6935b7aaed1f0f29b6028 (return statements), thanks!

Yes, the warnings are intentional.
