### ISSUE TITLE
Documentation out of date?

### ISSUE THREAD

**Issue by devicenull** [jedisct1/libsodium-php#147]
https://paragonie.com/book/pecl-libsodium/read/04-secretkey-crypto.md

It looks like since #116 the randombytes_buf function was dropped, but the documentation wasn't updated.

**Comment by paragonie-scott** [comment]
I've been busy the past few weeks, but will be deciding what to do with the documentation shortly.

**Comment by paragonie-scott** [comment]
This should be closable now. :)

**Comment by jedisct1** [comment]
Yay!
