### ISSUE TITLE
XAMPP - Call to undefined function

### ISSUE THREAD

**Issue by AFwcxx** [jedisct1/libsodium-php#150]
1. `extension=sodium.so` is in php.ini
2. `phpinfo()` shows that sodium is enabled
3. followed the [tutorial here](https://paragonie.com/book/pecl-libsodium/read/00-intro.md#installing-libsodium)
4. tried this:
`var_dump([
    sodium_library_version_major(),
    sodium_library_version_minor(),
    sodium_version_string()
]);`

Output:
`Error: Fatal error: Uncaught Error: Call to undefined function sodium_library_version_major()`

I've gone searching in Google to resolve this, but none seems to work :(

**Comment by jedisct1** [comment]
The PHP developers recommended these functions to be removed, and replaced with constants, to be more consistent with other extensions:

```
SODIUM_LIBRARY_VERSION
SODIUM_LIBRARY_MAJOR_VERSION
SODIUM_LIBRARY_MINOR_VERSION
```

So this is what was done.
