### ISSUE TITLE
scryptsalsa changes in libsodium

### ISSUE THREAD

**Issue by voitto** [jedisct1/libsodium-php#153]
i updated to libsodium 1.0.14 (compiled version 2.0.7) and PHP 7.1, i had the following code working with older php & sodium

seems the scryptsalsa has been deprecated? thanks for any advice

```php
function libsodium_scrypt($passwd) {
	return \Sodium\crypto_pwhash_scryptsalsa208sha256_str(
		$passwd,
		\Sodium\CRYPTO_PWHASH_SCRYPTSALSA208SHA256_OPSLIMIT_INTERACTIVE,
		\Sodium\CRYPTO_PWHASH_SCRYPTSALSA208SHA256_MEMLIMIT_INTERACTIVE
	);
}
function libsodium_scrypt_compare($passwd,$hash_str) {
	$valid = \Sodium\crypto_pwhash_scryptsalsa208sha256_str_verify( 
	  $hash_str,
	  $passwd
	);
	\Sodium\memzero( $passwd );
	return ($valid === TRUE);
}
```

**Comment by jedisct1** [comment]
The high-level pwhash API was introduced a long time ago. There's nothing wrong with scrypt, but this API is redundant, and having multiple, incompatible ways to achieve the same thing can be confusing.
And that means more things to maintain, test and document, and I'm lazy.

But if you were already using a password hashing function, migrating to a new one cannot be one instantaneously.

So, support for scrypt was re-added (cb8439599cf176c5d8da3f2d56fce1751625694d), but the functions spit out a deprecation warning.

**Comment by voitto** [comment]
thanks @jedisct1 Frank I appreciate your help! I was able to compile the latest libsodium-php and changed my code slightly 

<img width="546" alt="screen shot 2017-10-03 at 10 04 16 pm" src="https://user-images.githubusercontent.com/4466/31160691-1cd75e30-a887-11e7-9167-a2fde357bb32.png">
