### ISSUE TITLE
Invalid library (maybe not a PHP library) 'sodium.so' in Unknown on line 0 ....

### ISSUE THREAD

**Issue by v1n11** [jedisct1/libsodium-php#156]
Hi All,

I've been struggling since days to install libsodium on my Debian9/php7.0(with fpm) server ...
When I follow the steps outlined on https://paragonie.com/book/pecl-libsodium/read/00-intro.md#installing-libsodium everything seems to work, however I get this error at PHP startup:

Invalid library (maybe not a PHP library) 'sodium.so' in Unknown on line 0 ....

So the extension is not loaded ...

Hope someone can help me,
Thx !
Vincent.

**Comment by v1n11** [comment]
Looks like it was a version issue as per feedback I got here:
https://github.com/paragonie/halite/issues/48

**Comment by paragonie-security** [comment]
The weird thing is 2.0.9 is a bump of version 2.0.8 with no differences. So, something must've broke [here](https://github.com/jedisct1/libsodium-php/compare/2.0.7...2.0.9).

**Comment by jedisct1** [comment]
The funny thing is that it works if you don't install it using pecl :/

**Comment by paragonie-scott** [comment]
> I turned myself into a clusterfuck, Morty.
>
> I'm PECL RICK!

**Comment by jedisct1** [comment]
So, I retrieved the .tgz from PECL, ran "make install" on it, and it works.

I don't know what to do at this point.

**Comment by jedisct1** [comment]
Oh, even better:

```
Build process completed successfully
Installing '/usr/lib/php/20160303/sodium.so'
install ok: channel://pecl.php.net/libsodium-2.0.9
configuration option "php_ini" is not set to php.ini location

You should add "extension=sodium.so" to php.ini
[1]    14520 segmentation fault  sudo pecl install libsodium
```

Ok, time to hit the gym.

**Comment by jedisct1** [comment]
@remicollet Any idea?

**Comment by HazCod** [comment]
FYI, I temporarily use `pecl install -f libsodium-2.0.8` until this gets fixed.

**Comment by jedisct1** [comment]
Probably fixed. Yes, without changing anything to the code.
PECL is the worst package manager ever.

**Comment by remicollet** [comment]
>  PECL is the worst package manager ever.

This is the only one for C extension ;) 

BTW your package is corrupted, should have never provide the generated files:
- acinclude.m4
- aclocal.m4
- build/libtool.m4

This can only raise various issues on "some" target systems.

(and these files have changed, again, between 2.0.9 and 2.0.10)

**Comment by remicollet** [comment]
>  PECL is the worst package manager ever.

BTW, the distribution packager (rpm and yum/dnf, deb and apt-get, ...) is indeed **far better** ;)

* Linux users should use it to install PHP extension.
* Windows users should use the DLL provided on the pecl web site.
