### ISSUE TITLE
dont constantly warn for password hashing with ops at 1.

### ISSUE THREAD

**Issue by My1** [jedisct1/libsodium-php#159]
https://tools.ietf.org/html/draft-irtf-cfrg-argon2-03#section-9.4
recommends argon2id with one pass and max memory.

but
https://github.com/jedisct1/libsodium-php/blob/master/libsodium.c#L1786-L1789
kicks in when you go under the opslimit of interactive, regardless of whether you use more memory (which also means it takes more time) or not.

especially for servers that have more memory than computation available, setting the ops to 1 is the best thing they can do while keeping the RAM high. higher ops would also mean less RAM so that the time needed stays the same, which certainly doesnt make it better.

warning in general isnt bad, but maybe warn only if the compund of RAM AND ops is too low.

**Comment by My1** [comment]
thanks.

**Comment by remicollet** [comment]
What about a simple

```
if (val < min) {
   val =min;
   warning...
}
```

**Comment by My1** [comment]
that's also a nice idea, which is certainly not bad, since it 
1) doesnt break the application when someone totally overlooks it and
2) the warning can and (also should) contain the min val so this can be fixed.

**Comment by jedisct1** [comment]
I don't like it at all.

It means that the behavior would be inconsistent with all other platforms. A set of parameters that would be accepted by PHP due to internal magic would be refused by a Javascript client.

This would also hide bugs under the carpet. Using `0` due to weak typing would also appear to work just fine. That is not good. Raising an exception is really the thing to do here.

**Comment by remicollet** [comment]
@jedisct1 BTW, I have missed at first look at your change:

* warning for interactive value was dropped (subject of this issue)
* exception for minimal value was added (should probably have be a separate change)

So this indeed looks ok

(P.S. I have badly read as warning moved to exception which have been bad)
