### ISSUE TITLE
File Encryption Sample Implementation has a Bug

### ISSUE THREAD

**Issue by thomaskonrad** [jedisct1/libsodium-php#162]
I just used parts of your file encryption sample implementation (from `README.md`). What happens here is that the plain-text file is only read up to the the standard PHP file input buffer size, which is 8192 bytes by default. I think that in order to read an arbitrarily long file, it is supposed to look like this (use `feof()` instead of `stream_get_meta_data($fd_in)['unread_bytes']`):

```
list ($stream, $header) = sodium_crypto_secretstream_xchacha20poly1305_init_push($plainKey);

fwrite($output, $header);

$tag = SODIUM_CRYPTO_SECRETSTREAM_XCHACHA20POLY1305_TAG_MESSAGE;

do {
    $chunk = fread($input, self::CHUNK_SIZE);

    if (feof($input)) {
        $tag = SODIUM_CRYPTO_SECRETSTREAM_XCHACHA20POLY1305_TAG_FINAL;
    }

    $encrypted_chunk = sodium_crypto_secretstream_xchacha20poly1305_push($stream, $chunk, '', $tag);
    fwrite($output, $encrypted_chunk);
} while ($tag !== SODIUM_CRYPTO_SECRETSTREAM_XCHACHA20POLY1305_TAG_FINAL);

fclose($output);
fclose($input);
```

Cheers
Thomas

**Comment by jedisct1** [comment]
I don't know much about PHP, but it looks like `feof()` doesn't always return `TRUE` when the end of the file is reached. 

```sh
echo 1234567 > /tmp/a
```

```php
<?php
$input = fopen('/tmp/a', 'r');
for (;;) {
    $a = fread($input, 4);
    var_dump(strlen($a));
    if (feof($input)) {
        echo "END\n";
        break;
    }
}
fclose($input);
```

This damn thing prints:
```
4
4
0
```

`feof()` only returned `TRUE` after an extra `fread()` that returned nothing.

It works with `secretstream()`, but it adds a useless empty block at the end.

Do you know how to properly detect the end of a file in PHP?

**Comment by jedisct1** [comment]
We can retrieve the file length with `$in_len = fstat($fd_in)['size'];` and then check if `ftell($fd_in) >= $in_len`, but on 32-bit systems, I expect these functions to act funky with files larger than 2 GB.

**Comment by paragonie-scott** [comment]
PHP 7+ has universal bigint support, so for the current API that only supports PHP 7+, that is thankfully no longer a concern. :)

**Comment by jedisct1** [comment]
`int` is 64 bits everywhere now?

**Comment by nikic** [comment]
32-bit is still supported. Just less common, as Windows supports 64-bit now.

**Comment by jedisct1** [comment]
Looks like PHP's `ftell()` function returns a `zend_long`, and `zend_long` is an `int32_t` on 32-bit systems.

So, this is not an `off_t`. I don't think this works reliably with files > 2 GB.

**Comment by jedisct1** [comment]
Changed to use `feof()` in 98f24334044f8ee9ce075a92006cafc2d7303e91 until we find a reliable way to detect the end of a file in PHP.

**Comment by jedisct1** [comment]
One way to do it might be to check that `fread()` returns `0`, since it returns `FALSE` on error.

But this makes the examples less readable.

**Comment by timglabisch** [comment]
it tooked me a while to found a bug related to this issue.

i created a small wrapper around this lib, i've to crypt streams, files and strings.

when using streams, the code doesnt work, when directly reading from a resource it works well.


```php
$crypter = new LibsodiumCrypter("password", 1);

$fd_in = fopen('php://memory', 'w+b'); // doesnt work
fwrite($fd_in, file_get_contents('/tmp/example.original'));
rewind($fd_in);

#$fd_in = fopen('/tmp/example.original', 'rb'); // works 

$crypter->encryptResource($fd_in, $df_out);

```

to fix this issue i changed

```php
if (feof($fd_in));
```

to: 

```php
if (feof($fd_in) || $this->chunkSize > strlen($chunk));
```
