### ISSUE TITLE
Call to undefined function Sodium\randombytes_uniform

### ISSUE THREAD

**Issue by willysunny** [jedisct1/libsodium-php#163]
Similiar case to #110 

Using Nginx and Ubuntu 16.04, with PHP 7.1

Apparently when I tried to run the command `php -i | grep libsodium | wc -l`, I'm getting an error telling me that libsodium.so is an invalid library. (but I got a different number each time)

I've tried building from tar (stable), as well as from apt-get install libsodium-dev, as well as trying pecl install -f libsodium

none of the methods above is working =\

PS: I'm pretty safe to assume that sodium.so and libsodium.so are two different things, right? (since I found both files existed on my system, as well in my mods-available folder)

**Comment by willysunny** [comment]
This is what I got from `php -i | grep sodium`

Additional .ini files parsed => /etc/php/7.1/cli/conf.d/10-libsodium.ini,
/etc/php/7.1/cli/conf.d/20-sodium.ini,
sodium
sodium support => enabled
sodium compiled version => 2.0.10
libsodium headers version => 1.0.15
libsodium library version => 1.0.15

**Comment by jedisct1** [comment]
`libsodium.so` is the old name. So, if you have both, you should remove `libsodium.so`.

The `\Sodium` namespace doesn't exist any more either. Everything is in the global namespace now.

See the examples here: https://github.com/jedisct1/libsodium-php and the book here https://paragonie.com/book/pecl-libsodium

**Comment by willysunny** [comment]
So you mean I can just call randombytes_uniform anywhere and it should work as intended?

**Comment by jedisct1** [comment]
The `randombytes*()` functions have been removed, too, because PHP has already a [random_bytes](http://php.net/manual/en/function.random-bytes.php) function.

**Comment by jedisct1** [comment]
There's a `sodium_` prefix. So if `randombytes_uniform()` hadn't been removed, it would be accessible as `sodium_randombytes_uniform()`.

**Comment by developer-variety** [comment]
I am currently using PHP `7.2` with libsodium `1.0.16` and this function is `undefinded`.

Any update on this?

```php
    public static function generateStr($length)
    {
        $str = '';
        $keyspace = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890';

        $keysize = strlen($keyspace);
        for ($i = 0; $i < $length; $i++) {
            $str .= $keyspace[sodium_randombytes_uniform($keysize)];
        }

        return $str;
    }
```

**Comment by jedisct1** [comment]
Use PHP's [`random_int`](http://docs.php.net/manual/en/function.random-int.php) function.
