### ISSUE TITLE
Linker issue on crypto_pwhash_str on ubuntu(kernel 4.9) 

### ISSUE THREAD

**Issue by divyaksh-shukla** [jedisct1/libsodium-php#164]
```bash 
$ g++-4.9 sample.cpp -lsodium

/tmp/ccRdC5PP.o: In function `main':
sample.cpp:(.text+0x44): undefined reference to `crypto_pwhash_str'
collect2: error: ld returned 1 exit status
```
I've Followed the step in the documentation but could not get rid of this error. My cpp code is given below:
```cpp
#include <iostream>
#include <string.h>
#include "sodium.h"

#define PASSWORD "Here I am"

using namespace std;

int main() {
  char hashed_password[crypto_pwhash_STRBYTES];
  int result = 0;
  result = crypto_pwhash_str(hashed_password,PASSWORD,strlen(PASSWORD),crypto_pwhash_OPSLIMIT_INTERACTIVE,crypto_pwhash_MEMLIMIT_INTERACTIVE);
  cout<<"Password:"<<result<<endl;
  return 0;
}

```

I followed the same steps on redhat-6.8 (kernel 4.1 and g++ version 4.4) and it is working there. But on trying this on my home machine Ubuntu 16.04 (kernel 4.9 and g++ version 5.4) it gave the above error.

**Comment by jedisct1** [comment]
I'm a little bit surprised that `include "sodium.h"` didn't cause a preprocessor error.

Check that you don't have multiple installations of the library. Maybe a dead old one in `/usr/` and another in `/usr/local/`

**Comment by divyaksh-shukla** [comment]
There is no dead installation of sodium in `/usr/`. But I tried to compile with this command
```bash
$ g++ sample.cpp /usr/local/lib/libsodium.a -o sample
```
and everything worked fine. Is there any alternative to doing this?. My code was unchanged.

**Comment by jedisct1** [comment]
Pretty sure you have multiple versions installed.
