### ISSUE TITLE
Cannot use sodium_crypto_pwhash with the SODIUM_CRYPTO_PWHASH_ALG_ARGON2I13 algorithm

### ISSUE THREAD

**Issue by Ovski4** [jedisct1/libsodium-php#165]
Hi,

We encountered an issue with the libsodium php extension and are trying to fix it.

- We were running PHP **7.1.7** in Ubuntu 14.04.5 LTS.
- The libsodium extension was in version **1.0.6**
- When running this command: `php --ri libsodium`, we had this output

```
libsodiumlibsodium support => enabled
libsodium compiled version => 1.0.6
libsodium headers version => 1.0.10
libsodium library version => 1.0.10
```

Everything was working fine until one day on another machine the hash generated was different. Apparently the command `apt-get install libsodium-dev` was ran and the libsodium version changed. The php extension version remains the same (**1.0.6**) but the command `php --ri libsodium` gives us;

```
libsodiumlibsodium support => enabled
libsodium compiled version => 1.0.6
libsodium headers version => 1.0.16
libsodium library version => 1.0.16
```

But we can't downgrade the libsodium-dev package (unless we compile it manually which we don't want to do)

So we tried to update the PHP version from 7.1 to **7.2**, since the libsodium extension is a core function since that version.

We had the following function

```
private function getHashedPassword($username, $rawPassword, $salt = null)
{
    $salt = empty($salt) ? \Sodium\randombytes_buf(\Sodium\CRYPTO_PWHASH_SALTBYTES) : hex2bin($salt);
    $hashed = \Sodium\crypto_pwhash(
        \Sodium\CRYPTO_SIGN_SEEDBYTES,
        $rawPassword,
        $salt,
        \Sodium\CRYPTO_PWHASH_OPSLIMIT_INTERACTIVE,
        \Sodium\CRYPTO_PWHASH_MEMLIMIT_INTERACTIVE
    );

    return bin2hex($hashed);
}
```

That we changed to this one, with the new argument to specify the algorithm:

```
private function getHashedPassword($username, $rawPassword, $salt = null)
{
    $salt = empty($salt) ? sodium_randombytes_buf(SODIUM_CRYPTO_PWHASH_SALTBYTES) : hex2bin($salt);
    $hashed = sodium_crypto_pwhash(
        SODIUM_CRYPTO_SIGN_SEEDBYTES,
        $rawPassword,
        $salt,
        SODIUM_CRYPTO_PWHASH_OPSLIMIT_INTERACTIVE,
        SODIUM_CRYPTO_PWHASH_MEMLIMIT_INTERACTIVE,
        SODIUM_CRYPTO_PWHASH_ALG_ARGON2I13
    );

    return bin2hex($hashed);
}
```

But when calling this function now we get those errors:

```
Fatal error: Uncaught SodiumException: internal error in ... on line ...
SodiumException: internal error in ... on line ...
```

We have 2 questions:
- How is it we can't use the ARGON2I13 algorithm? What did we do wrong?
- Is it a normal that even if the php extension was the same on 2 different machines (1.0.6), the behaviour of the \Sodium\crypto_pwhash function was different because of the libsodum-dev package?

Thank you for your help!

**Comment by jedisct1** [comment]
When hashing a password without using pwhash_str you must save the function parameters in order to recompute the same value later. See the libsodium documentation or the php-libsodium example https://github.com/jedisct1/libsodium-php#encrypt-a-file-using-a-key-derived-from-a-password

SODIUM_CRYPTO_PWHASH_OPSLIMIT_INTERACTIVE and other example values can change and did change.

**Comment by Ovski4** [comment]
We noticed that those constants changed between the 2 versions. We hard-coded every parameter from version 1.0.10 to 1.0.16 and the result is still different. That's the reason why we would like to try by specifying an other algorithm, without success so far.

We rolled back to php version 7.1, updated the php extension to 2.0.10 which is the latest stable one on pecl (We are still using libsodium in version 1.0.16)

We tried to display the constants but we can't find one that correspond to an algorithm.

```
$constants = get_defined_constants(true);
var_dump($constants['libsodium']);

array (size=58)
  'Sodium\CRYPTO_AEAD_AES256GCM_KEYBYTES' => int 32
  'Sodium\CRYPTO_AEAD_AES256GCM_NSECBYTES' => int 0
  'Sodium\CRYPTO_AEAD_AES256GCM_NPUBBYTES' => int 12
  'Sodium\CRYPTO_AEAD_AES256GCM_ABYTES' => int 16
  'Sodium\CRYPTO_AEAD_CHACHA20POLY1305_KEYBYTES' => int 32
  'Sodium\CRYPTO_AEAD_CHACHA20POLY1305_NSECBYTES' => int 0
  'Sodium\CRYPTO_AEAD_CHACHA20POLY1305_NPUBBYTES' => int 8
  'Sodium\CRYPTO_AEAD_CHACHA20POLY1305_ABYTES' => int 16
  'Sodium\CRYPTO_AEAD_CHACHA20POLY1305_IETF_KEYBYTES' => int 32
  'Sodium\CRYPTO_AEAD_CHACHA20POLY1305_IETF_NSECBYTES' => int 0
  'Sodium\CRYPTO_AEAD_CHACHA20POLY1305_IETF_NPUBBYTES' => int 12
  'Sodium\CRYPTO_AEAD_CHACHA20POLY1305_IETF_ABYTES' => int 16
  'Sodium\CRYPTO_AUTH_BYTES' => int 32
  'Sodium\CRYPTO_AUTH_KEYBYTES' => int 32
  'Sodium\CRYPTO_BOX_SEALBYTES' => int 48
  'Sodium\CRYPTO_BOX_SECRETKEYBYTES' => int 32
  'Sodium\CRYPTO_BOX_PUBLICKEYBYTES' => int 32
  'Sodium\CRYPTO_BOX_KEYPAIRBYTES' => int 64
  'Sodium\CRYPTO_BOX_MACBYTES' => int 16
  'Sodium\CRYPTO_BOX_NONCEBYTES' => int 24
  'Sodium\CRYPTO_BOX_SEEDBYTES' => int 32
  'Sodium\CRYPTO_KX_BYTES' => int 32
  'Sodium\CRYPTO_KX_PUBLICKEYBYTES' => int 32
  'Sodium\CRYPTO_KX_SECRETKEYBYTES' => int 32
  'Sodium\CRYPTO_GENERICHASH_BYTES' => int 32
  'Sodium\CRYPTO_GENERICHASH_BYTES_MIN' => int 16
  'Sodium\CRYPTO_GENERICHASH_BYTES_MAX' => int 64
  'Sodium\CRYPTO_GENERICHASH_KEYBYTES' => int 32
  'Sodium\CRYPTO_GENERICHASH_KEYBYTES_MIN' => int 16
  'Sodium\CRYPTO_GENERICHASH_KEYBYTES_MAX' => int 64
  'Sodium\CRYPTO_PWHASH_SALTBYTES' => int 16
  'Sodium\CRYPTO_PWHASH_STRPREFIX' => string '$argon2id$' (length=10)
  'Sodium\CRYPTO_PWHASH_OPSLIMIT_INTERACTIVE' => int 2
  'Sodium\CRYPTO_PWHASH_MEMLIMIT_INTERACTIVE' => int 67108864
  'Sodium\CRYPTO_PWHASH_OPSLIMIT_MODERATE' => int 3
  'Sodium\CRYPTO_PWHASH_MEMLIMIT_MODERATE' => int 268435456
  'Sodium\CRYPTO_PWHASH_OPSLIMIT_SENSITIVE' => int 4
  'Sodium\CRYPTO_PWHASH_MEMLIMIT_SENSITIVE' => int 1073741824
  'Sodium\CRYPTO_PWHASH_SCRYPTSALSA208SHA256_SALTBYTES' => int 32
  'Sodium\CRYPTO_PWHASH_SCRYPTSALSA208SHA256_STRPREFIX' => string '$7$' (length=3)
  'Sodium\CRYPTO_PWHASH_SCRYPTSALSA208SHA256_OPSLIMIT_INTERACTIVE' => int 524288
  'Sodium\CRYPTO_PWHASH_SCRYPTSALSA208SHA256_MEMLIMIT_INTERACTIVE' => int 16777216
  'Sodium\CRYPTO_PWHASH_SCRYPTSALSA208SHA256_OPSLIMIT_SENSITIVE' => int 33554432
  'Sodium\CRYPTO_PWHASH_SCRYPTSALSA208SHA256_MEMLIMIT_SENSITIVE' => int 1073741824
  'Sodium\CRYPTO_SCALARMULT_BYTES' => int 32
  'Sodium\CRYPTO_SCALARMULT_SCALARBYTES' => int 32
  'Sodium\CRYPTO_SHORTHASH_BYTES' => int 8
  'Sodium\CRYPTO_SHORTHASH_KEYBYTES' => int 16
  'Sodium\CRYPTO_SECRETBOX_KEYBYTES' => int 32
  'Sodium\CRYPTO_SECRETBOX_MACBYTES' => int 16
  'Sodium\CRYPTO_SECRETBOX_NONCEBYTES' => int 24
  'Sodium\CRYPTO_SIGN_BYTES' => int 64
  'Sodium\CRYPTO_SIGN_SEEDBYTES' => int 32
  'Sodium\CRYPTO_SIGN_PUBLICKEYBYTES' => int 32
  'Sodium\CRYPTO_SIGN_SECRETKEYBYTES' => int 64
  'Sodium\CRYPTO_SIGN_KEYPAIRBYTES' => int 96
  'Sodium\CRYPTO_STREAM_NONCEBYTES' => int 24
  'Sodium\CRYPTO_STREAM_KEYBYTES' => int 32
```

Even with a dummy integer as a 6th parameter, we got 

```
Sodium\crypto_pwhash() expects exactly 5 parameters, 6 given 
```

Which tell us there is no way to specify the algo.

The release notes state that we should be able to specify the old algorithm, but we were not able to find information in the documentation about that. 

![release_notes](https://user-images.githubusercontent.com/1218714/36398251-0b1ee55c-162b-11e8-9fb3-10a913a0658c.png)

Is the pecl extension up to date with the latest version of libsodium?

**Comment by Ovski4** [comment]
We also notice that you wrote tests for the ALGON2ID algorithm but not for the old one https://github.com/jedisct1/libsodium-php/blob/master/tests/pwhash_argon2i.phpt#L32-L42

**Comment by jedisct1** [comment]
The optional parameter in `sodium_crypto_pwhash()` is only available with versions 2.x of the PECL module, not with the version using the `\Sodium\` namespace as you seem to be using.

**Comment by Ovski4** [comment]
Yes we figured that out. We are using it the proper way, without the namespace (version 2.0.10)

**Comment by jedisct1** [comment]
What are the values for opslimit and memlimit?

**Comment by Ovski4** [comment]
SODIUM_CRYPTO_PWHASH_OPSLIMIT_INTERACTIVE = 2 SODIUM_CRYPTO_PWHASH_MEMLIMIT_INTERACTIVE = 67108864

**Comment by Ovski4** [comment]
I updated the `tests/pwhash_argon2i.phpt` file by adding that code at the end

```
$key = sodium_crypto_pwhash
  ($out_len, $passwd, $salt,
   SODIUM_CRYPTO_PWHASH_OPSLIMIT_INTERACTIVE,
   SODIUM_CRYPTO_PWHASH_MEMLIMIT_INTERACTIVE,
   SODIUM_CRYPTO_PWHASH_ALG_ARGON2I13);
var_dump(strlen($key) === $out_len);
```
I got this error when running it with the CLI:

```
PHP Fatal error:  Uncaught SodiumException: internal error in /home/vagrant/libsodium-php/tests/pwhash_argon2i.phpt:48
```

Maybe you could tried that as well to see if you have the same error.

**Comment by jedisct1** [comment]
`SODIUM_CRYPTO_PWHASH_OPSLIMIT_INTERACTIVE` => values below 3 are refused with Argon2i and I think they always did.

**Comment by jedisct1** [comment]
Looking at the headers of version 1.0.10, even if that version is dead old:

```c
#define crypto_pwhash_argon2i_OPSLIMIT_INTERACTIVE 4ULL
#define crypto_pwhash_argon2i_MEMLIMIT_INTERACTIVE 33554432ULL
```

So, if you used these symbols,`opslimit` was `4` and `memlimit` ` 33554432`.

**Comment by Ovski4** [comment]
Yes indeed!

The same old hash is generated with those parameters:
```
private function getHashedPassword($username, $rawPassword, $salt = null)
{
    $salt = empty($salt) ? sodium_randombytes_buf(SODIUM_CRYPTO_PWHASH_SALTBYTES) : hex2bin($salt);
    $hashed = sodium_crypto_pwhash(
        SODIUM_CRYPTO_SIGN_SEEDBYTES,
        $rawPassword,
        $salt,
        4,
        33554432,
        SODIUM_CRYPTO_PWHASH_ALG_ARGON2I13
    );

    return bin2hex($hashed);
}
```

Un grand merci pour la réactivité à toute épreuve 👍
