### ISSUE TITLE
PHP 7.2.5 Extension not loaded

### ISSUE THREAD

**Issue by Sparkeroo96** [jedisct1/libsodium-php#172]
Reposting this as I put it the wrong library

I a running xampp with php 7.2.5
When I run get_loaded_extensions(), sodium is not loaded up but in the phpinfo under modules I can see Sodium and Author "Frank Denis"

I tried
var_dump([ SODIUM_LIBRARY_MAJOR_VERSION, SODIUM_LIBRARY_MINOR_VERSION, SODIUM_LIBRARY_VERSION ]);
and I got
Warning: Use of undefined constant SODIUM_LIBRARY_MAJOR_VERSION - assumed 'SODIUM_LIBRARY_MAJOR_VERSION'
for each of them

I have also followed this guide:
https://paragonie.com/book/pecl-libsodium/read/00-intro.md#installing-libsodium
and seen no results, do you know what I have done wrong

Had this commented before
"But XAMPP probably doesn't include support for libsodium."
If it doesnt work with xampp, how would you conduct testing on local?

**Comment by Sparkeroo96** [comment]
I have tried it with and without the PECL extension it mentions in the guide

**Comment by WhiteLoti** [comment]
So I was stuck where you are. As of right now, PHP 7.2 has libsodium and libsodium-dev in the Linux repositories but they are unable to interact with PHP via a script from my experience. However, the CLI works. My suggestion would be to downgrade to 7.1 because 7.2 is still in development I think. Then follow the instructions for windows via the paragonie website.

**Comment by paragonie-scott** [comment]
Did you install the `libsodium` extension (i.e. v1.x) or the `sodium` extension (v2.x)? The API changed between the two, because of a decision made with the vote that got libsodium into PHP 7.2,

You also may need to check that the `php.ini` for apache matches the CLI `php.ini`.

**Comment by WhiteLoti** [comment]
Not that I am doubting you got it to work with your systems, but I confirmed this with my colleague who was working with a RedHat Enterprise Linux v7 machine. He had the same problem as I did when running the extension in PHP 7.2.9. I am pretty sure we exhausted all the solutions. We followed the exact instructions from the documentation for installing the libsodium & libsodium-dev from the yum repository. We then used PECL install -f libsodium to try to make the extension work. We put sodium.so in all the places we could think of where Apache would read server configurations. We also tried creating a ini file in the /etc/php.d directory. We restarted httpd several hundred times (no joke). Then tested the extension in the command line with php -i | grep sodium. It was loaded ** The problem arises when you need to run the sodium from a php script not in the command line. ** I tried both syntax of the crypto_secretbox_keygen() function. The namespace version \Sodium\crypto_secretbox_keygen() and the sodium_crypto_secretbox_keygen(). Both return undefined function when run in a script. ** It works in the command line like in the example but that is mostly useless. ** I did the exact same thing except with PHP v7.1.21 and it works perfectly in the php script. @paragonie-scott or @jedisct1 ** My definitive conclusion is that libsodium does not work in the PHP v7.2.9 in a php script. It works fine in PHP v7.1.* ** Could you test the actual sodium in a php script that is ** not run through the command line. **

**Comment by paragonie-scott** [comment]
When you say "in a PHP script" you mean "in a PHP script executed by a web browser", right?

This points to an Apache/nginx/etc. configuration issue.

**Comment by jedisct1** [comment]
Try creating a web page that just calls `phpinfo()` so you can see where the `php.ini` files are searched for, when PHP is used as an Apache module or via php-fpm.

It's common for distributions to use different `php.ini` files for CLI usage and for web services.

**Comment by WhiteLoti** [comment]
@paragonie-scott We are not running nginx or php-fpm on the instance running PHP v7.2.9. Just to be sure, we uninstalled php-fpm and nginx. We checked that Apache was only reading from the httpd.conf in the /etc/httpd/conf/ directory

@jedisct1 I did the sodium extension does not show up in the phpfo(INFO_MODULES) or phpinfo when run through the browser. If I use the php script with phpinfo through the cli it will work and sodium shows up.

**Comment by paragonie-scott** [comment]
Okay, there should be **another** php.ini file for Apache.

https://stackoverflow.com/a/17850801/2224584

**Comment by jedisct1** [comment]
In the `phpinfo()` output, what you should look for is the paths to the INI files.

**Comment by WhiteLoti** [comment]
@jedisct1 in enterprise linux (EL) systems they can be loaded dynamically from the /etc/php.d/ directory. We also tried manually by giving a direct path in the php.ini files, so "/usr/lib64/php/modules/sodium.so" and  "/usr/lib64/php/modules/sodium." Neither worked.

**Comment by WhiteLoti** [comment]
@paragonie-scott I saw that post and tried it a long time ago. One comment is for the CLI which I am not interested. The other talked about it for a php script via the web browser. Still did not work.

**Comment by paragonie-scott** [comment]
Is there a Red Hat bug for this issue?

**Comment by WhiteLoti** [comment]
@paragonie-scott I would not think so it if made it into the EPEL repository. It is not like the package is broken or wrong in anyway except that Apache does not load when running any form of PHP 7.2.*. Unless there is some unknown compilation error in PHP 7.2 itself. As I mentioned before, it runs fine in the command line in PHP 7.2.* Probably because it uses php-cli instead of the Apache web server. **Everything works as expected in PHP 7.1.***

**Comment by jedisct1** [comment]
How did you install PHP 7.2? It doesn't seem to be part of any RHEL release.

**Comment by WhiteLoti** [comment]
@jedisct1 
This is the link to the Fedora v27 repository. 
http://rpms.remirepo.net/fedora/remi-release-27.rpm

This is the instructions my colleague used. You have to use the yum-config-manager to set it to install PHP 7.1.21 otherwise it defaults to PHP 7.2.9
https://blog.remirepo.net/post/2016/12/05/Install-PHP-7.1-on-CentOS-RHEL-or-Fedora

**Comment by paragonie-scott** [comment]
I would expect anything from @remicollet to work on those operating systems, and I would expect Remi's PHP 7.2 to ship with libsodium.

The general troubleshooting workflow I would follow is:

 - [ ] Is mod_php enabled?
 - [ ] Are PHP scripts executing?
 - [ ] Is Apache loading PHP 7.2?
 - [ ] Which configuration files are being loaded by Apache?
 - [ ] Does the php.ini file used by Apache + mod_php contain `extension=sodium`?

**Comment by WhiteLoti** [comment]
@paragonie-scott you are correct that PHP 7.2 ships with libsodium. But when checking the loaded extensions, sodium in a PHP Script running in the browser using phpinfo() does not show up. It will show up in the command line. I followed all the steps mentioned above on Fedora. I will have to ask my colleague tomorrow about what he did on RedHat. It is close to midnight so he will respond till tomorrow.

**Comment by paragonie-scott** [comment]
PHP scripts don't run in the browser, they run in an Apache module. The issue is almost certainly that Apache isn't loading the sodium extension (probably because the Apache php.ini is not configured to do so, but the CLI php.ini is, so you only see it in a CLI environment).

**Comment by WhiteLoti** [comment]
@paragonie-scott not to be rude or sound arrogant but I tried placing the extension=sodium.so && extension=sodium everywhere Apache loads extensions. I even checked with the phpinfo in a browser to see which directory Apache load extensions from. I also exhausted all the php.ini && httpd.conf as mentioned before. I have installed several extensions before including igbinary and phpredis from their binaries. So I am pretty confident I know what I am doing.

**Comment by remicollet** [comment]
On a fresh EL-7 installation:

```
# yum-config-manager --enable remi-php72
# yum install httpd php php-sodium
# service httpd start
# php --ri sodium

sodium

sodium support => enabled
libsodium headers version => 1.0.16
libsodium library version => 1.0.16

```
And same think in the browser.

**Comment by WhiteLoti** [comment]
The php-sodium package didn’t show up when I ran “yum list sodium” only libsodium showed up.

**Comment by remicollet** [comment]
@WhiteLoti check enabled repositories.

**Comment by akadebnath** [comment]
Though this thread is a couple of month old and you may have found a solution already, I am posting this here so that it may help someone like you and I.

After trying all the options discussed above, **I finally resolved it by below solution**:

Step 1: Open C:\xampp\php\php.ini and add below extension:
extension=php_sodium.dll
No 'sodium' extension was present there, even in commented (;) state. So I had to add the line.

Step 2: Copy C:\xampp\php\libsodium.dll and paste it in below path:
C:\xampp\apache\bin

I restarted the Apache server and the browser is loading the extension perfectly!

**Comment by WhiteLoti** [comment]
@akadebnath we were talking about in a linux environment, which is more complicated than windows environment in terms of setup.

**Comment by Sparkeroo96** [comment]
Sorry pal, in the existing setting it was running on windows 10

**Comment by akadebnath** [comment]
@WhiteLoti I am sorry that it would not work for you. But it may help someone who is reading this thread and uses windows environment.

**Comment by WhiteLoti** [comment]
I got it to work. As you mentioned earlier this is an old thread. We finally got it to work after countless days of trying. We could only get it to work on PHP v7.1.x. So following the website’s instructions we got it to work up to PHP v7.1.9 but anything PHP v7.2.x is broken in the compilation of the code. Funny thing is we moved to NodeJS 😅

**Comment by donksly** [comment]
I had this issue on windows, my solution was quite simple, add the PHP extension to the environment variable on windows as such: https://john-dugan.com/add-php-windows-path-variable/

**Comment by gnicol-bzh** [comment]
The solution suggested by @akadebnath [here](https://github.com/jedisct1/libsodium-php/issues/172#issuecomment-441038440) worked for me. Thank you!

````
Windows 10
WAMPSERVER 3.1.0 64bit
PHP 7.0.24
php libsodium 2.0.21-7.1 ts vc14 x64
```

**Comment by askew-etc** [comment]
> 
> 
> Though this thread is a couple of month old and you may have found a solution already, I am posting this here so that it may help someone like you and I.
> 
> After trying all the options discussed above, **I finally resolved it by below solution**:
> 
> Step 1: Open C:\xampp\php\php.ini and add below extension:
> extension=php_sodium.dll
> No 'sodium' extension was present there, even in commented (;) state. So I had to add the line.
> 
> Step 2: Copy C:\xampp\php\libsodium.dll and paste it in below path:
> C:\xampp\apache\bin
> 
> I restarted the Apache server and the browser is loading the extension perfectly!

If I could give you money I would, I've been banging my head against the wall for almost three days trying to get this to work. THANK YOU!!!
