### ISSUE TITLE
Wrong version of libsodium found

### ISSUE THREAD

**Issue by WhiteLoti** [jedisct1/libsodium-php#176]
I went to make the extension and got the following error:

`
configure: error: libsodium lib (< 1.0.8) or lib not found
`

Is that a mistake because directly on the repository it says libsodium >= 1.0.9 and PHP >= 7.0

I have libsodium 1.0.14 version installed and sodium compiled version 2.012 which was recommended according to the comments on the repository.

**Comment by jedisct1** [comment]
Thanks!

The build script will now reject version 1.0.8, and require at least 1.0.9 as documented.
