### ISSUE TITLE
Segmentation Error

### ISSUE THREAD

**Issue by WhiteLoti** [jedisct1/libsodium-php#177]
I am not sure if you also manage the pecl libsodium but I tried to use the pecl install -f libsodium. It seems to run okay except the last line.
`You should add "extension=sodium.so" to php.ini
Segmentation fault (core dumped)
`

I'm wondering if this is preventing apache from loading the module because I never see it in phpinfo(). Can you specify which directory is needed when using the --with-sodium[=DIR] option on ./configure

**Comment by ryandiamond23** [comment]
@WhiteLoti What was your solution here?

**Comment by WhiteLoti** [comment]
Can you give me a little background on the system you are running it on?
What OS and version?
Which PHP you are using?
