### ISSUE TITLE
Missing functionality for Authenticated Encryption with Associated Data (AEAD)

### ISSUE THREAD

**Issue by b354c502** [jedisct1/libsodium-php#18]
The current library doesn't support AEAD.  For example, crypto_secretbox accepts a nonce, but that nonce must either be stored externally (inconvenient) or; be appended/prepended to the ciphertext post-encryption (not included in the poly1305-MAC, and as such subject to tampering).  It would be great if crypto_aead_chacha20poly1305_encrypt (http://doc.libsodium.org/secret-key_cryptography/aead.html) could be implemented.  

Also, the following functions being implemented would make life less painful:

- crypto_scalarmult
- crypto_sign_ed25519_pk_to_curve25519
- crypto_sign_ed25519_sk_to_curve25519

Direct access the diffie-hellman functions would enable the user to use stream ciphers directly (shared-keys can't currently be generated directly by the user).  And being able to convert ED25519 keys to curve25519 keys opens up new possibilities in encrypt/sign functionality.

Sorry to be cheeky, but it would be great if all this could be pushed to the PECL package! (the recent updates to crypto_stream() are not yet available)

Wonderful work so far, your library has been infinitely useful... I hope you continue to develop it in the future.  Many thanks!

**Comment by jedisct1** [comment]
AEAD is done.

**Comment by jedisct1** [comment]
Scalar multiplication has been added.

I'm a bit reluctant to adding key conversion functions (or any low-level functions) to these bindings.

**Comment by paragonie-scott** [comment]
> I'm a bit reluctant to adding key conversion functions (or any low-level functions) to these bindings.

I don't see them as necessary, for the following reasons:

1. Feature creep.
2. Does the benefit PHP developers get out of this access greatly exceed the harm they can inflict on their users?
3. Feature creep.
4. Generating encryption keys is cheap.
5. Feature creep.

That said, if `crypto_seal()` and `crypto_seal_open()` come to fruition, I would like to eventually see bindings for them in PHP (and other programming languages).
