### ISSUE TITLE
sodium_crypto_pwhash question

### ISSUE THREAD

**Issue by WhiteLoti** [jedisct1/libsodium-php#180]
I know the sodium_crypto_pwhash is specifically designed and used for passphrase hashing but would it be a bad idea to use it for a cross-site request forgery token? I was thinking because you can adjust the ops and memory limit. It would be a decent defense mechanism against possible cross site request forgery. I am not a cryptographer by any means, just an academic.

**Comment by paragonie-scott** [comment]
`sodium_crypto_pwhash` is overkill for CSRF prevention. You only want pwhash for passwords. Instead, you want challenge-response authentication based on a long, random secret.

```php
$_SESSION['csrf_secret'] = sodium_bin2hex(random_bytes(32));
/* ... snip ... */
if (hash_equals($_SESSION['csrf_secret'], $_POST['csrf_secret'])) {
    /* No CSRF here, chief! */
}
```

Also, SameSite cookies.
