### ISSUE TITLE
File encryption in php and decryption in android (java) and vice versa with xchacha20

### ISSUE THREAD

**Issue by mohamadali1374** [jedisct1/libsodium-php#181]
Hi

I want to encrypt files in php , and decrypt them in android (java), and I want use  xchacha20.

so the general question : how to encrypt files in php and decrypt them  on android securely ans fast with xchacha20?

thanks...

**Comment by jedisct1** [comment]
The PHP extension has an example on [how to encrypt a file using a secret key](https://github.com/jedisct1/libsodium-php#encrypt-a-file-using-a-secret-key).

I'm not familiar with the Java bindings, but they probably have a similar API.
