### ISSUE TITLE
sodium_base642bin no padding urlsafe varient throwing exception on decoding

### ISSUE THREAD

**Issue by arosolino** [jedisct1/libsodium-php#182]
```php
$bin = random_bytes(32);
$encoded = sodium_bin2base64($bin, SODIUM_BASE64_VARIANT_URLSAFE_NO_PADDING);
$decoded = sodium_base642bin($encoded, SODIUM_BASE64_VARIANT_URLSAFE_NO_PADDING);
```

The code above throws
`Fatal error: Uncaught SodiumException: invalid base64 string`

This issue was reported in #171, but only SODIUM_BASE64_VARIANT_ORIGINAL_NO_PADDING was tested for and not SODIUM_BASE64_VARIANT_URLSAFE_NO_PADDING.

Thanks

**Comment by jedisct1** [comment]
Fixed, thank you!
