### ISSUE TITLE
Forgot to bump PHP_SODIUM_VERSION 

### ISSUE THREAD

**Issue by arosolino** [jedisct1/libsodium-php#183]
Hi

In the last update it seems you forgot to bump PHP_SODIUM_VERSION 

Thanks

**Comment by jedisct1** [comment]
Indeed :( The PECL release system is so archaic that I always screw up something.

**Comment by tessus** [comment]
ah, that's probably the reason why `pecl install` does not work to upgrade to 2.0.14.

**Comment by tessus** [comment]
Sorry, I think this has nothing to do with it after all. I'll open another issue. I don't want to hijack this one.
