### ISSUE TITLE
pecl install/upgrade does not install 2.0.14

### ISSUE THREAD

**Issue by tessus** [jedisct1/libsodium-php#185]
For some reason `pecl install` nor `pecl upgrade` upgrades to the latest version. 
Currently there doesn't seem to be a way to use `pecl` to get and compile 2.0.14.

First I thought it's because of #183, but the meta data in `package.xml` looks correct.

Any chance you could create a new release (or update the current one)?

**Comment by tessus** [comment]
Additional info:

```
# pecl list
INSTALLED PACKAGES, CHANNEL PECL.PHP.NET:
=========================================
PACKAGE   VERSION STATE
libsodium 2.0.13  stable

# pecl upgrade libsodium
Nothing to upgrade

# pecl install libsodium
pecl/libsodium is already installed and is the same as the released version 2.0.13
install failed
```

**Comment by calind** [comment]
For me fails with:
```
Failed to download pecl/libsodium, version "2.0.15", latest release is version 2.0.13, stability "stable", use "channel://pecl.php.net/libsodium-2.0.13" to install
```

**Comment by tessus** [comment]
Yea, it's an issue with pecl. For a few weeks no submitted packages were indexed, thus they won't show up (as an update). I've sent an email to the pecl mailinglist and I was told they would be re-indexed. Unfortunately this hasn't happened yet or it has, but ran into errors.
