### ISSUE TITLE
PECL Installation Issues

### ISSUE THREAD

**Issue by sarciszewski** [jedisct1/libsodium-php#19]
If you try to install the PECL package without having already compiled libsodium, this is the output it gives you.
```sh
root@devbox:/home/developer# pecl install channel://pecl.php.net/libsodium-0.1.1downloading libsodium-0.1.1.tgz ...
Starting to download libsodium-0.1.1.tgz (162,027 bytes)
..................................done: 162,027 bytes
8 source files, building
running: phpize
Configuring for:
PHP Api Version:         20090626
Zend Module Api No:      20090626
Zend Extension Api No:   220090626
building in /tmp/pear/temp/pear-build-rootmBcHGX/libsodium-0.1.1
running: /tmp/pear/temp/libsodium/configure
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for a sed that does not truncate output... /bin/sed
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... i686-pc-linux-gnu
checking host system type... i686-pc-linux-gnu
checking target system type... i686-pc-linux-gnu
checking for PHP prefix... /usr
checking for PHP includes... -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64
checking for PHP extension directory... /usr/lib/php5/20090626+lfs
checking for PHP installed headers prefix... /usr/include/php5
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... no
configure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate PHP parsers.
checking for gawk... no
checking for nawk... nawk
checking if nawk is broken... no
checking for libsodium support... yes, shared
checking for libsodium files in default path... not found
configure: error: Please reinstall the libsodium distribution
ERROR: `/tmp/pear/temp/libsodium/configure' failed
root@devbox:/home/developer# 
```
The solution, I suspect, will be getting libsodium packages in the major Linux distributions so when users encounter this problem, the answer can be as simple as `apt-get install libsodium`.

In the meantime, is there any way to make compilation failures due to libsodium not existing give more information on how to get libsodium installed? I may know how to do it, but that doesn't mean everyone else will. (Perhaps a link to a documentation page somewhere?)

(Note: I'm going to be setting up a PPA for libsodium tonight.)

**Comment by jedisct1** [comment]
Hi,

The link to the libsodium documentation has been added (and sadly, it's over HTTP due to Gitbook restrictions, but I am going to set up a TLS terminator to work around this before the next PECL release).

**Comment by sarciszewski** [comment]
This is probably a stupid question, but: Do you need any help setting it up? :)

**Comment by jedisct1** [comment]
Sadly the certificate is only valid for `download.libsodium.org`.

https://download.libsodium.org/doc/ can be used to browse the documentation over TLS, but I'm looking for a better option. Cloudflare is an option, but they don't support DNSSEC yet.

**Comment by sarciszewski** [comment]
I'm curious why [DNSSEC](http://sockpuppet.org/blog/2015/01/15/against-dnssec/) would be a blocker here.

**Comment by jedisct1** [comment]
DNS can be used to verify the files available for download, as an alternative to PGP:

    $ drill -D TXT libsodium-1.0.2-msvc.zip.download.libsodium.org.
    "5001f96885e069ccd6b45e012b0873d40faa5ffb83e8addd704269608fb653df"

    $ sha256 libsodium-1.0.2-msvc.zip
    5001f96885e069ccd6b45e012b0873d40faa5ffb83e8addd704269608fb653df

This obviously requires DNSSEC.

That said, I take it back, Cloudflare wouldn't actually solve anything here.

Until Let's Encrypt becomes a reality, I guess https://download.libsodium.org/doc/ will be the way to browse the doc over TLS.
