### ISSUE TITLE
Version mismatch 2.0.21

### ISSUE THREAD

**Issue by agentile** [jedisct1/libsodium-php#195]
Hello, it looks like with the latest 2.0.21 , the version was not properly updated similar to what was done for 2.0.20 . So I've installed 2.0.21 but it shows 2.0.20

```
[root@test libsodium-2.0.21]# php -i | grep "sodium"
/etc/php-7.2.d/20-sodium.ini,
sodium
sodium support => enabled
sodium compiled version => 2.0.20
```

https://github.com/jedisct1/libsodium-php/blob/master/php_libsodium.h#L8

https://github.com/jedisct1/libsodium-php/commit/f86db50e3fd85954e17f1f55985426daab335724

**Comment by jedisct1** [comment]
I'll try to think about it for the next version :)
