### ISSUE TITLE
Dont restrict SALT to SODIUM_CRYPTO_PWHASH_SALTBYTES

### ISSUE THREAD

**Issue by jobs-git** [jedisct1/libsodium-php#196]

**Comment by jedisct1** [comment]
libsodium doesn't let you change that parameter, so the PHP bindings can't expose something that doesn't exist.

If, for some reason, you have to use a salt of a different size, you can always hash it to get a salt which is `SODIUM_CRYPTO_PWHASH_SALTBYTES` bytes long.

**Comment by jobs-git** [comment]
Hi, this is why I submitted this issue, so that the parameter should be exposed

**Comment by jedisct1** [comment]
This parameter does not exist: https://download.libsodium.org/doc/password_hashing/the_argon2i_function#key-derivation

So the PHP wrappers cannot expose it.

**Comment by jobs-git** [comment]
I think this should be updated somehow? https://github.com/jedisct1/libsodium/blob/927dfe8e2eaa86160d3ba12a7e3258fbc322909c/src/libsodium/include/sodium/crypto_pwhash_argon2i.h

Should I file the issue there?

**Comment by jedisct1** [comment]
`#define crypto_pwhash_argon2i_SALTBYTES 16U`

That looks like a constant to me.

**Comment by jedisct1** [comment]
Regarding the salt length, the Argon2 document says: "128 bits is sufficient for all applications, but can be reduced to 64 bits in the case of space constraints".

If you need a shorter salt, you can always pad it to 128 bits before calling the function.

**Comment by jobs-git** [comment]
I made a mistake up there, but I am looking for a longer salt, cause Quantum computers are now in development and it is expected to crack 30 million years in just 12 days. So longer salt is needed.

**Comment by jedisct1** [comment]
Quantum computers do not have any advantage over classical computers for breaking hash functions. They would even be *slower* than an exhaustive search.

Also, a salt is not a key. Salts should be considered public.

**Comment by jobs-git** [comment]
If that is your argument, I still see this as a ticket for design issue, I hope this stays open until somebody implements it.

**Comment by jedisct1** [comment]
This will not be implemented, sorry.
