### ISSUE TITLE
same issue on ubuntu-16.04

### ISSUE THREAD

**Issue by kramskj** [jedisct1/libsodium-php#199]
The only library apt-get is aware of, at least on my ubunti, is libsodium18 ... there appears to be no way to select "sodium" mentioned above as the new version of "libsodium".

Having been through the gamut of installing libsodium18, and libsodium-dev (just in case), then 
sudo pecl install of libsodium, the sodium.so file did not have execute permissions, whereas all the other extensions did.  So changed that.  

Added the line "extension=sodium.so" to the php.ini file mentioned by phpinfo().

Running the php cli, sodium is found, and works.

Accessing a php script via Apache2 (i.e in response to browser request) does not work.

Not being either an Apache2 or php installation expert, I am now stumped.

Any suggestions (polite ones :-)    ) please?

I've scoured the Internet, and no one has found a slouton yet, other than reverting to php7.1

Many thanks, Jerry

**Comment by soatok** [comment]
Silly question: is `libsodium23` available after you run `apt-get update`?

**Comment by jedisct1** [comment]
Did you look at `phpinfo()` served by Apache?

The `php.ini` file may be different when using the CLI and when using Apache.

**Comment by kramskj** [comment]
I have got to the point where some of libsodium is available to PHP7, via either the CLI or via Apache.

But, using nm -g sodium.so shows many undefineds, and no symbols that start sodium_

I don't know how the symbols are mapped into PHP space.  Regardless, there are no symbols that vaguely match randombytes_buf, nor randombytes_close.

Clearly though, the PHP environment (7.2) is missing some of the sodium APIs.  The ones that are present can be called just using the function name, without mentioning the \Sodium\ namespace, and if the namespace is included, then PHP can't resolve the sysmbol.

Here's what I did to install:

sudo apt-get update && sudo apt-get install libsodium-dev;
sudo pecl install -f libsodium

I edited the php.ini file, and changed sodium.so to have file permissions 755 (it didn't have execute permissions).

I then restarted php-fpm, apache and mysql.

Here is the nm output ...

                 U add_next_index_stringl
                 U _array_init
0000000000215368 B __bss_start
                 U convert_to_null
                 U crypto_aead_aes256gcm_decrypt
                 U crypto_aead_aes256gcm_encrypt
                 U crypto_aead_aes256gcm_is_available
                 U crypto_aead_chacha20poly1305_decrypt
                 U crypto_aead_chacha20poly1305_encrypt
                 U crypto_aead_chacha20poly1305_ietf_decrypt
                 U crypto_aead_chacha20poly1305_ietf_encrypt
                 U crypto_auth
                 U crypto_auth_verify
                 U crypto_box_easy
                 U crypto_box_keypair
                 U crypto_box_open_easy
                 U crypto_box_seal
                 U crypto_box_seal_open
                 U crypto_box_seed_keypair
                 U crypto_generichash
                 U crypto_generichash_blake2b_salt_personal
                 U crypto_generichash_final
                 U crypto_generichash_init
                 U crypto_generichash_update
                 U crypto_pwhash_scryptsalsa208sha256
                 U crypto_pwhash_scryptsalsa208sha256_memlimit_interactive
                 U crypto_pwhash_scryptsalsa208sha256_memlimit_sensitive
                 U crypto_pwhash_scryptsalsa208sha256_opslimit_interactive
                 U crypto_pwhash_scryptsalsa208sha256_opslimit_sensitive
                 U crypto_pwhash_scryptsalsa208sha256_str
                 U crypto_pwhash_scryptsalsa208sha256_str_verify
                 U crypto_scalarmult
                 U crypto_scalarmult_base
                 U crypto_secretbox_easy
                 U crypto_secretbox_open_easy
                 U crypto_shorthash
                 U crypto_sign
                 U crypto_sign_detached
                 U crypto_sign_ed25519_pk_to_curve25519
                 U crypto_sign_ed25519_sk_to_curve25519
                 U crypto_sign_ed25519_sk_to_pk
                 U crypto_sign_keypair
                 U crypto_sign_open
                 U crypto_sign_seed_keypair
                 U crypto_sign_verify_detached
                 U crypto_stream
                 U crypto_stream_xor
                 w __cxa_finalize@@GLIBC_2.2.5
0000000000215368 D _edata
                 U _efree
                 U _emalloc
0000000000215378 B _end
000000000000fe98 T _fini
                 U free@@GLIBC_2.2.5
0000000000004ee0 T get_module
                 w __gmon_start__
0000000000004898 T _init
                 w _ITM_deregisterTMCloneTable
                 w _ITM_registerTMCloneTable
                 w _Jv_RegisterClasses
                 U memcpy@@GLIBC_2.14
                 U memset@@GLIBC_2.2.5
                 U php_info_print_table_end
                 U php_info_print_table_header
                 U php_info_print_table_row
                 U php_info_print_table_start
                 U randombytes_buf
                 U randombytes_close
                 U sodium_add
                 U sodium_bin2hex
                 U sodium_compare
                 U sodium_hex2bin
                 U sodium_increment
                 U sodium_init
                 U sodium_library_version_major
                 U sodium_library_version_minor
                 U sodium_memcmp
                 U sodium_memzero
00000000002152c0 D sodium_module_entry
                 U sodium_version_string
                 U __stack_chk_fail@@GLIBC_2.4
                 U zend_ce_exception
                 U zend_error
                 U zend_error_noreturn
                 U zend_hash_clean
                 U zend_hash_str_find
                 U __zend_malloc
                 U zend_new_interned_string
                 U zend_parse_parameters
                 U zend_read_property
                 U zend_register_internal_class_ex
                 U zend_register_long_constant
                 U zend_register_string_constant
                 U zend_throw_exception
000000000000612c T zif_sodium_add
000000000000caff T zif_sodium_bin2hex
000000000000e557 T zif_sodium_compare
000000000000b784 T zif_sodium_crypto_aead_aes256gcm_decrypt
000000000000b390 T zif_sodium_crypto_aead_aes256gcm_encrypt
000000000000b32b T zif_sodium_crypto_aead_aes256gcm_is_available
000000000000e629 T zif_sodium_crypto_aead_aes256gcm_keygen
000000000000bf44 T zif_sodium_crypto_aead_chacha20poly1305_decrypt
000000000000bb83 T zif_sodium_crypto_aead_chacha20poly1305_encrypt
000000000000c700 T zif_sodium_crypto_aead_chacha20poly1305_ietf_decrypt
000000000000c30c T zif_sodium_crypto_aead_chacha20poly1305_ietf_encrypt
000000000000e93d T zif_sodium_crypto_aead_chacha20poly1305_ietf_keygen
000000000000e7b3 T zif_sodium_crypto_aead_chacha20poly1305_keygen
000000000000de9b T zif_sodium_crypto_auth
000000000000eac7 T zif_sodium_crypto_auth_keygen
000000000000e08d T zif_sodium_crypto_auth_verify
00000000000083e9 T zif_sodium_crypto_box
0000000000007815 T zif_sodium_crypto_box_keypair
0000000000007c74 T zif_sodium_crypto_box_keypair_from_secretkey_and_publickey
00000000000086ef T zif_sodium_crypto_box_open
0000000000008064 T zif_sodium_crypto_box_publickey
000000000000822b T zif_sodium_crypto_box_publickey_from_secretkey
00000000000089d8 T zif_sodium_crypto_box_seal
0000000000008c59 T zif_sodium_crypto_box_seal_open
0000000000007ea1 T zif_sodium_crypto_box_secretkey
0000000000007a1f T zif_sodium_crypto_box_seed_keypair
0000000000006b09 T zif_sodium_crypto_generichash
00000000000073a1 T zif_sodium_crypto_generichash_final
0000000000006dee T zif_sodium_crypto_generichash_init
000000000000ec51 T zif_sodium_crypto_generichash_keygen
000000000000715b T zif_sodium_crypto_generichash_update
000000000000f3f1 T zif_sodium_crypto_kdf_derive_from_key
000000000000eddb T zif_sodium_crypto_kdf_keygen
000000000000d9b7 T zif_sodium_crypto_kx_client_session_keys
000000000000d478 T zif_sodium_crypto_kx_keypair
000000000000d7f0 T zif_sodium_crypto_kx_publickey
000000000000d62d T zif_sodium_crypto_kx_secretkey
000000000000d25f T zif_sodium_crypto_kx_seed_keypair
000000000000dc29 T zif_sodium_crypto_kx_server_session_keys
000000000000ab03 T zif_sodium_crypto_pwhash_scryptsalsa208sha256
000000000000aeea T zif_sodium_crypto_pwhash_scryptsalsa208sha256_str
000000000000b205 T zif_sodium_crypto_pwhash_scryptsalsa208sha256_str_verify
000000000000d00c T zif_sodium_crypto_scalarmult
000000000000657d T zif_sodium_crypto_secretbox
000000000000ef65 T zif_sodium_crypto_secretbox_keygen
0000000000006850 T zif_sodium_crypto_secretbox_open
0000000000006333 T zif_sodium_crypto_shorthash
000000000000f0ef T zif_sodium_crypto_shorthash_keygen
0000000000009adf T zif_sodium_crypto_sign
000000000000a152 T zif_sodium_crypto_sign_detached
000000000000e378 T zif_sodium_crypto_sign_ed25519_pk_to_curve25519
000000000000e199 T zif_sodium_crypto_sign_ed25519_sk_to_curve25519
0000000000008eea T zif_sodium_crypto_sign_keypair
0000000000009349 T zif_sodium_crypto_sign_keypair_from_secretkey_and_publickey
0000000000009e21 T zif_sodium_crypto_sign_open
0000000000009918 T zif_sodium_crypto_sign_publickey
0000000000009576 T zif_sodium_crypto_sign_publickey_from_secretkey
0000000000009755 T zif_sodium_crypto_sign_secretkey
00000000000090f4 T zif_sodium_crypto_sign_seed_keypair
000000000000a468 T zif_sodium_crypto_sign_verify_detached
000000000000a574 T zif_sodium_crypto_stream
000000000000f267 T zif_sodium_crypto_stream_keygen
000000000000a846 T zif_sodium_crypto_stream_xor
000000000000cce7 T zif_sodium_hex2bin
000000000000602e T zif_sodium_increment
0000000000006261 T zif_sodium_memcmp
0000000000005ec6 T zif_sodium_memzero
000000000000f778 T zif_sodium_pad
000000000000fb40 T zif_sodium_unpad
0000000000005e38 T zm_info_sodium
0000000000005e1e T zm_shutdown_sodium
00000000000052af T zm_startup_sodium

**Comment by jedisct1** [comment]
PHP has `random_bytes()` since PHP 7.0.0.

So the libsodium RNG is not exposed in PHP.

**Comment by kramskj** [comment]
Don't know what RNG is?   Some of the sodium APIs are callable and work inside a php script.  Others are missing.  

How much is this is due to problems in the .so, and how much downstram ini how PHP hooks up to the .so code?   Should I be fetching a different version of libsodium to the above to acquire randombytes_buff().  Where from?

I'm amazed that the stack provider (bitnami) doesn't have all this preconfigured and working for Ubuntu 16, given the ramifications of GDPR.

So any guidance much apreciated!  We have a product to launch, and getting encryption sorted out is the only thing preventing us.

**Comment by jedisct1** [comment]
RNG is random number generator.

The `randombytes_*()` functions are not present -- they used to be present, but PHP developers pointed out that they were redundant with the existing `random_bytes()` functions, so they were removed.

PHP's `random_bytes()` function is just as secure anyway, since the code is very similar.

**Comment by jedisct1** [comment]
All the [examples](https://github.com/jedisct1/libsodium-php) use `random_bytes()` for that reason.

**Comment by kramskj** [comment]
Hi Frank,

Can't thank you enough.  Your examples work fine.

Unfortunately, https://www.php.net/manual/en/book.sodium.php links to 
https://paragonie.com/book/pecl-libsodium, which uses randombytes*

Issue definitely closed.

Best wishes, Jerry

Jerry Kramskoy,  CEO/CTO MusicIncite Ltd.

+44 (0)208 004 9122
276 Ewell Rd, Surbiton, Surrey, KT6 7AG
Registered in England and Wales.  Company Number:  08651718
https://emuso.buzz
