### ISSUE TITLE
Missing API Coverage

### ISSUE THREAD

**Issue by sarciszewski** [jedisct1/libsodium-php#20]
Now that I've had a bit more practice with C (and PHP's internals), I'll probably send a PR for this soon.

We're missing some features in the PECL extension:

* `crypto_sign_detached()` and `crypto_sign_verify_detached()`
* `sodium_bin2hex()` and `sodium_hex2bin()`
* Possibly others

**Comment by jedisct1** [comment]
Don't know what you are talking about. `crypto_sign_detached()` and `crypto_sign_verify_detached()` are in.

Ok, maybe I just added them :)

**Comment by sarciszewski** [comment]
Haha, okay thanks a lot. Now I just have to wait for the next PECL release to use them in my project :)
