### ISSUE TITLE
crypto_box_*(): derivating order of public + secret keypair in >= PHP 7.2

### ISSUE THREAD

**Issue by Kaulkwappe** [jedisct1/libsodium-php#200]
Regarding #https://github.com/jedisct1/libsodium/issues/904:

That means once [\sodium_crypto_box_publickey()](https://www.php.net/manual/en/function.sodium-crypto-box-publickey.php) and [\sodium_crypto_box_secretkey()](https://www.php.net/manual/en/function.sodium-crypto-box-secretkey.php) have been used to store the keys, one has to be aware that PHP functions such as [\sodium_crypto_box_seal_open()](https://www.php.net/manual/en/function.sodium-crypto-box-seal-open.php) have to be called with the order secret, public once those keys are concatenated later:

`\sodium_crypto_box_seal_open($ciphertext, $secretKey . $publicKey);`

Same applies as well to [\sodium_crypto_box_keypair_from_secretkey_and_publickey()](https://www.php.net/manual/en/function.sodium-crypto-box-keypair-from-secretkey-and-publickey.php):

`\sodium_crypto_box_keypair_from_secretkey_and_publickey($secretKey, $publicKey);`

**Comment by jedisct1** [comment]
Key pairs must be treated as opaque structures.

You can pass them as-is to `box_seal_open` (please don't try rebuilding them by concatenating random things), create one with `keypair_from_secretkey_and_publickey()`, or extract individual keys with `box_publickey` and `box_secretkey`.

They may become objects, or include a key type in a future version.

**Comment by Kaulkwappe** [comment]
Thanks! Insofar this would be the right way to go:

```
\sodium_crypto_box_seal_open(
	$ciphertext,
	\sodium_crypto_box_keypair_from_secretkey_and_publickey($fromDatabase_RawSecretKeyDecrypted, $fromDatabase_RawPublicKey)
);
```

**Comment by jedisct1** [comment]
Yes.

**Comment by Kaulkwappe** [comment]
I will now add this note to the PHP docs, if I can:

> Keypairs must be treated as opaque data types which can change in future releases. Use sodium_crypto_box_secretkey() and sodium_crypto_box_publickey() to get the corresponding secret/public key and sodium_crypto_box_keypair_from_secretkey_and_publickey() to rebuilt a keypair.
