### ISSUE TITLE
Plaintext message length limit

### ISSUE THREAD

**Issue by Kaulkwappe** [jedisct1/libsodium-php#201]
Some time ago I read something about a limit for the message length when using functions such as

[\sodium_crypto_aead_xchacha20poly1305_ietf_encrypt()](https://www.php.net/manual/de/function.sodium-crypto-aead-xchacha20poly1305-ietf-encrypt.php)
[\sodium_crypto_aead_xchacha20poly1305_ietf_decrypt()](https://www.php.net/manual/de/function.sodium-crypto-aead-xchacha20poly1305-ietf-decrypt.php) 

since they load the full message or ciphertext into the memory and working with large data (e.g. files) could cause performance issues.

Unfortunately I am not able to find the article where I read about this. As far as I understand it, one can encrypt megabytes or even gigabytes in one pass, but the suggestion was to use chunks of 16K for better performance.

What is the current suggestion for files and for larger messages (up to 256K) which are not files?

**Comment by jedisct1** [comment]
Use secretstream: https://github.com/jedisct1/libsodium-php#encrypt-a-file-using-a-secret-key

**Comment by jedisct1** [comment]
secretstream works for anything, not just files.

**Comment by jedisct1** [comment]
https://download.libsodium.org/doc/secret-key_cryptography/secretstream

**Comment by Kaulkwappe** [comment]
Ahh, perfect. However, using the non-stream function for messages up to 256K should be fine, or not?

**Comment by jedisct1** [comment]
Yes, that's totally fine.
