### ISSUE TITLE
Duplicate argument names for sodium_crypto_secretstream_xchacha20poly1305_pull/push

### ISSUE THREAD

**Issue by TysonAndre** [jedisct1/libsodium-php#206]
https://github.com/jedisct1/libsodium-php/blob/28d13bf437cb969a0583031fc7ac54c5a8dc8116/libsodium.c#L166-L179 uses the argument name $string twice - the signature is equivalent to

```
function sodium_crypto_secretstream_xchacha20poly1305_pull(&$state, $string, $string = null) {}
function sodium_crypto_secretstream_xchacha20poly1305_push(&$state, $string, $string = null, $long = null) {}
```

PHP 8.0 introduces named arguments in https://wiki.php.net/rfc/named_params and repeating argument names will cause problems. It's also unexpected because user-defined functions can't do that.

https://github.com/php/php-src/blob/master/build/gen_stub.php may help if you want to rename parameters instead of just ensuring uniqueness - it adds an option such as `/** @generate-legacy-arginfo */` that can be used to generate _arginfo.h and .c files from `.stub.php` files such as https://github.com/krakjoe/apcu/blob/master/apc_iterator.stub.php

(I know php 8.0 isn't supported yet by libsodium - I'm working on seeing if parameter type info and parameter names are consistent with documentation and other information about function/method types for many other extensions)

**Comment by jedisct1** [comment]
Thank you!

So, what should be done in order to fix this? Just replace one of the `string` with anything else?

**Comment by TysonAndre** [comment]
Yes. At minimum, changing it to string1 and string2 would fix this (or even just one of the names) - I'm new to the codebase.

Ideally, there would be named arguments that would reflect the data that this expects. $ad doesn't seem too descriptive.

~~From the README.md, I'd assume that $chunk might be appropriate for the second parameter and $ad for the second, but I'm not at all familiar with this codebase and docs on php.net aren't descriptive https://www.php.net/manual/en/function.sodium-crypto-secretstream-xchacha20poly1305-push.php~~


```
sodium_crypto_secretstream_xchacha20poly1305_pull ( string &$state , string $c [, string $ad ] ) : array
sodium_crypto_secretstream_xchacha20poly1305_push ( string &$state , string $msg [, string $ad [, int $tag ]] ) : string
```

Changing this to pull($state, $cipherText, $associatedData) and push($state, $msg, $associatedData = default, $tag = default) may make sense based on https://google.github.io/tink/javadoc/tink/HEAD-SNAPSHOT/com/google/crypto/tink/subtle/XChaCha20Poly1305.html

**Comment by TysonAndre** [comment]
Sorry, I forgot about the history of this extension - I assume that a copy of this was moved into core in php 7.3, but not all php installations are bundled with it.

https://github.com/php/php-src/blob/master/ext/sodium/libsodium.stub.php has all of the names used in php-src - If you want `pecl install libsodium` to work even in php 7.3 (or even 8.0) with as few issues as possible, using the names that that stub file uses would make sense

**Comment by nikic** [comment]
As this extension has been bundled with PHP since PHP 7.2, I don't think there's much value in making the PECL extension compatible with newer versions. Or at least it's not really obvious to me in which circumstances one would install the PECL extension rather than the bundled one?

**Comment by jedisct1** [comment]
The code included with PHP is a bit behind the one from the PECL extension.

For dumb practical reasons. I never understood how to indent code as in the extension bundled with PHP, nor how to test it as easily as a standalone module.

So, everything is written in the PECL module first and then possibly backported into PHP, manually reindented line by line. This is a little bit painful and actually the main reason I haven't touched that code for quite some time.

**Comment by TysonAndre** [comment]
> So, everything is written in the PECL module first and then possibly backported into PHP, manually reindented line by line. This is a little bit painful and actually the main reason I haven't touched that code for quite some time.

php-src had a `.editorconfig` file - **many editors support the option to reindent a selection of code inline to an indentation level and tab style** (e.g. ctrl+space in eclipse, `=` in vim, most modern editors/IDEs should have some way to do this) - in php it's tabs

```
[{*.{awk,bat,c,cpp,d,h,l,re,skl,w32,y},Makefile*}]
indent_size              = 4
indent_style             = tab
```


> For dumb practical reasons. I never understood how to indent code as in the extension bundled with PHP, nor how to test it as easily as a standalone module.

`phpize; ./configure; make clean test` can test it in a given php version on linux/mac.
On windows, https://wiki.php.net/internals/windows/stepbystepbuild_sdk_2#building_pecl_extensions (`nmake test` to test?)

`.travis.yml` only includes 7.0, 7.1, and 7.2 - including any newer versions that you intend to support may help, e.g. I've seen commits for 7.3 and tests work in 7.4.

- I just use the version bundled with php-src

**Comment by jedisct1** [comment]
> php-src had a `.editorconfig` file

But that doesn't format C code. Is there for example a `clang-format` configuration for PHP code? I tried [that gist](https://gist.github.com/realityking/c61e6b31248b5f37da67), but the result wasn't great due to macros being used to define functions (`PHP_FE`...)

> phpize; ./configure; make clean test can test it in a given php version on linux/mac.

PHP (standard installation on Mac with Homebrew) already includes the sodium extension, so that doesn't work unless the extension name is renamed before testing. Is there a way to work around that? (I use Debian that has PHP 7.0 without libsodium in order to test the extension, but there must be an easier way...)

**Comment by TysonAndre** [comment]
> But that doesn't format C code. Is there for example a clang-format configuration for PHP code? I tried that gist, but the result wasn't great due to macros being used to define functions (PHP_FE...)

I've tried the same and had no luck either - https://github.com/runkit7/runkit7/blob/master/.clang-format.example is probably worse, and php-src has a lot of macros that don't obey the indentation rules you'd expect for function calls (e.g. arginfo, foreach macros, etc)

Is that a statically compiled extension? If it isn't, there's probably an ini file containing `extension=sodium` or sodium.so in one of the files/folders mentioned by `php --ini`

I guess you could try docker or building php from source - https://www.php.net/manual/en/install.macosx.compile.php doesn't seem helpful but homebrew may provide the dependencies/build tools. I don't use macs.

`./buildconf --force; ./configure --disable-all --with-zlib --with-zip --enable-phar --with-bz2  --enable-opcache --with-readline --enable-json --enable-soap --enable-tokenizer --prefix=$HOME/php-8.0.0-dev-install --with-libxml  --enable-filter --enable-iconv --enable-mbstring; make -j9 --enable-openssl --with-curl --with-gmp; make -j4; make install` might work - `./configure --help` would tell you how to build any additional dependencies.

- Some of those configure options can be left out or need to be added; that's what I use for a minimal install for an unrelated option

**Comment by jedisct1** [comment]
Anyway, PECL version 2.0.23 has been released and is compatible with PHP 8.

Thanks!

**Comment by TysonAndre** [comment]
Should I create a new issue for making sure the PECL extension uses the same argument names as the php extensions?

It may be a cause for confusion, bugs in deployed code using named arguments, and bug reports to php or the pecl's issue tracker if `sodium_crypto_auth(message: 'message', key: 'some key')` works if an end user using the version from php-src but doesn't if you're using the version from the PECL (for new features, or because of unfamiliarity with the sodium installation process)

- The pecl uses `$string`, not `$message`

**Comment by jedisct1** [comment]
A pull request would be way better 👍 

Looks like in PHP 8, the function signatures are generated from a description and each function gets its own type, even if it is redundant.

That makes things way easier to maintain than having to keep track of every possible signature and coming up with insane names for them.

So having that would definitely be great. However `ZEND_BEGIN_ARG_WITH_RETURN_TYPE_MASK_EX` was introduced in PHP 8, so it may need emulation on PHP 7.

**Comment by TysonAndre** [comment]
> Looks like in PHP 8, the function signatures are generated from a description and each function gets its own type, even if it is redundant.

If the function signature is exactly the same (including parameter names), it's a `#define` to reuse the memory, and the names would be human readable.


> So having that would definitely be great. However ZEND_BEGIN_ARG_WITH_RETURN_TYPE_MASK_EX was introduced in PHP 8, so it may need emulation on PHP 7.

I mentioned that stubs had support for php 7 - unavailable functionality is probably avoided with macros - I forget how far back it supports

> https://github.com/php/php-src/blob/master/build/gen_stub.php may help if you want to rename parameters instead of just ensuring uniqueness - **it adds an option `/** @generate-legacy-arginfo */` that can be used to generate _arginfo.h (and a different legacy header file for php 7 using macros to support older versions)** and .c files from .stub.php files such as https://github.com/krakjoe/apcu/blob/master/apc_iterator.stub.php

**Comment by TysonAndre** [comment]
```

// build/gen_stub.php
    public function discardInfoForOldPhpVersions(): void {
        $this->return->type = null;
        foreach ($this->args as $arg) {
            $arg->type = null;
            $arg->defaultValue = null;
        }
    }
```

Oh. That's disappointing, it erases the types entirely.

https://github.com/runkit7/runkit7/blob/4.0.0a2/runkit.c#L21-L27 - you can use macros for some functionality, though it's inconvenient to continue supporting old php versions for the lack of nullable types and changes to the argument count expected by _EX macros.

You could have a different stub file for php 7 and avoid nullable/union types?

**Comment by TysonAndre** [comment]
> A pull request would be way better :+1:

I've been busy with many other things related to php 8.0 and probably won't have time to do that; filed an issue to keep track of it in case anyone encounters this issue or wants to pick it up

**Comment by jedisct1** [comment]
Don't worry, I didn't expect anything.

That has been done in bc13305ee9939551ef3aa05397100c7fee5f4d21
