### ISSUE TITLE
Make this PECL use the same parameter names as php-src/ext/sodium ?

### ISSUE THREAD

**Issue by TysonAndre** [jedisct1/libsodium-php#207]
PHP 8.0 supports named arguments. This extension also supports php 8.0, and adds new features before they're available in php 8

It may be a cause for confusion, bugs in deployed code using named arguments, and bug reports to php or the pecl's issue tracker if function calls such as `sodium_crypto_auth(message: 'message', key: 'some key')` works if an end user using the version from php-src but doesn't if you're using the version from the PECL (for new features, or because of unfamiliarity with the sodium installation process)

- The pecl uses `$string`, not `$message`

See discussion in https://github.com/jedisct1/libsodium-php/issues/206#issuecomment-739546144

Possibilities:
1. Use the stubs only for php 8, keep existing arg info for php 7
2. Use stubs for all versions, and add C macros to convert unsupported functionality to supported macros, e.g. https://github.com/runkit7/runkit7/blob/4.0.0a2/runkit.c#L21-L27
    `#undef` based on PHP_VERSION_ID and looking at the original macro in php-src for those branches may help in redefining macros for php 7.0 and 7.1 if php 7.1/7.0 support can't be dropped - but it's really verbose
3. Use a different set of stubs for php 8 and php 7

-------

(Noticed while trying to make parameter name info consistent between reflection and other sources of type/parameter name info for dozens of extensions)

**Comment by jedisct1** [comment]
Done in bc13305ee9939551ef3aa05397100c7fee5f4d21

**Comment by TysonAndre** [comment]
```
 cc -I. -I/path/to/programming/libsodium-php -DPHP_ATOM_INC -I/path/to/programming/libsodium-php/include -I/path/to/programming/libsodium-php/main -I/path/to/programming/libsodium-php -I/path/to/php-7.0.33-nts-install/include/php -I/path/to/php-7.0.33-nts-install/include/php/main -I/path/to/php-7.0.33-nts-install/include/php/TSRM -I/path/to/php-7.0.33-nts-install/include/php/Zend -I/path/to/php-7.0.33-nts-install/include/php/ext -I/path/to/php-7.0.33-nts-install/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /path/to/programming/libsodium-php/libsodium.c  -fPIC -DPIC -o .libs/libsodium.o
In file included from /path/to/programming/libsodium-php/libsodium.c:89:
/path/to/programming/libsodium-php/libsodium_arginfo.h:4:109: error: macro "ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX" requires 6 arguments, but only 5 given
    4 | ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_sodium_crypto_aead_aes256gcm_is_available, 0, 0, _IS_BOOL, 0)
      |                                                                                                             ^
In file included from /path/to/php-7.0.33-nts-install/include/php/main/php.h:39,
                 from /path/to/programming/libsodium-php/libsodium.c:10:
/path/to/php-7.0.33-nts-install/include/php/Zend/zend_API.h:111: note: macro "ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX" defined here
  111 | #define ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(name, return_reference, required_num_args, type, class_name, allow_null) \
      | 
/path/to/php-7.0.33-nts-install/include/php/Zend/zend_API.h:122:30: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘}’ token
  122 | #define ZEND_END_ARG_INFO()  };
      |                              ^
/path/to/programming/libsodium-php/libsodium_arginfo.h:5:1: note: in expansion of macro ‘ZEND_END_ARG_INFO’
    5 | ZEND_END_ARG_INFO()
      | ^~~~~~~~~~~~~~~~~
In file included from /path/to/programming/libsodium-php/libsodium.c:89:
/path/to/programming/libsodium-php/libsodium_arginfo.h:17:105: error: macro "ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX" requires 6 arguments, but only 5 given
   17 | ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_sodium_crypto_aead_aes256gcm_encrypt, 0, 4, IS_STRING, 0)
      |                                                                                                         ^
In file included from /path/to/php-7.0.33-nts-install/include/php/main/php.h:39,
                 from /path/to/programming/libsodium-php/libsodium.c:10:
/path/to/php-7.0.33-nts-install/include/php/Zend/zend_API.h:111: note: macro "ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX" defined here
  111 | #define ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(name, return_reference, required_num_args, type, class_name, allow_null) \
      | 
/path/to/php-7.0.33-nts-install/include/php/Zend/zend_API.h:107:70: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
  107 | #define ZEND_ARG_TYPE_INFO(pass_by_ref, name, type_hint, allow_null) { #name, NULL, type_hint, pass_by_ref, allow_null, 0 },
      |                                                                      ^
/path/to/programming/libsodium-php/libsodium_arginfo.h:18:2: note: in expansion of macro ‘ZEND_ARG_TYPE_INFO’
   18 |  ZEND_ARG_TYPE_INFO(0, message, IS_STRING, 0)
      |  ^~~~~~~~~~~~~~~~~~
```

FYI @jedisct1 - Travis tests will fail in php 7.0 when travis finally starts. The macros have different arg counts in php 7.1 and/or 7.0

> #undef based on PHP_VERSION_ID and looking at the original macro in php-src for those branches may help in redefining macros for php 7.0 and 7.1 if php 7.1/7.0 support can't be dropped - but it's really verbose

**Comment by TysonAndre** [comment]
Also, it'd make help to check in the `.stub.php` file used, even with TODOs if some additional changes were made manually

**Comment by jedisct1** [comment]
PHP 7.0 and PHP 7.1 don't seem to compile any more on current macOS versions.

Could you possibly fix this?

**Comment by jedisct1** [comment]
The `stub.php` file has been added!
