### ISSUE TITLE
Inconsistent error message for sodium_crypto_sign_open and sodium_crypto_sign_verify_detached

### ISSUE THREAD

**Issue by vijayaraghavanramanan** [jedisct1/libsodium-php#210]
The function `sodium_crypto_sign_verify_detached` throws an error if argument 1 isn't SODIUM_CRYPTO_SIGN_BYTES bytes long but `sodium_crypto_sign_open` doesn't.

Is there a reason for it?

Using PHP 8 on Windows 10.

**Comment by paragonie-security** [comment]
Incompatible use-cases.

* `crypto_sign_verify_detached($signature, $message, $pubKey):  bool`
* `crypto_sign_open($signedMessage, $pubKey)`

In the latter case, you have the signature concatenated with the message as one bundle. Therefore, the length check doesn't make sense.
