### ISSUE TITLE
run pecl install -f libsodium-1.0.7.tgz 

### ISSUE THREAD

**Issue by jasonxiaoqin** [jedisct1/libsodium-php#213]
![image](https://user-images.githubusercontent.com/24785358/116643196-13b00c00-a9a3-11eb-8671-a1bc0f6307aa.png)

**Comment by jedisct1** [comment]
Hi,

Unfortunately I can't read the image. What does it say?

**Comment by jedisct1** [comment]
And the current version is 2.0.25.

Version 1.0.x had a nice API but they are completely unsupported now.
