### ISSUE TITLE
Php 8.1 support

### ISSUE THREAD

**Issue by henrikschytte** [jedisct1/libsodium-php#221]
Will it support php8.1 soon .?

**Comment by yauhenko** [comment]
Is there any way to use libsodium in php 8.1 ?

**Comment by jedisct1** [comment]
Yes. Enable the libsodium extension, which is part of the standard PHP distribution :)

**Comment by imaadghouri85** [comment]
Hello @jedisct1 

I don't see **libsodium** module in php-8.1 hence not able to enable it within php.ini file. 

Are we sure it is part of php-8.1 ?

`bash-4.2# php --version
PHP 8.1.16 (cli) (built: Mar 23 2023 19:44:24) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.16, Copyright (c) Zend Technologies
bash-4.2# ls -l /usr/lib64/php/modules/*sodium*
ls: cannot access /usr/lib64/php/modules/*sodium*: No such file or directory
bash-4.2# php -m | grep -i sodium
bash-4.2# 
bash-4.2# 
`

**Comment by imaadghouri85** [comment]
Also @jedisct1 

When I tried to compile the code and then install it with pecl, it is now failing with below error:

`
bash-4.2# pecl install libsodium
pecl/libsodium requires PHP (version >= 7.0.0, version <= 8.0.99), installed version is 8.1.16
No valid packages found
install failed
`
