### ISSUE TITLE
Issues in sodium_crypto_kdf_derive_from_key

### ISSUE THREAD

**Issue by Coxxs** [jedisct1/libsodium-php#223]
As libsodium's documentation [says](https://libsodium.gitbook.io/doc/key_derivation#key-derivation-with-libsodium-greater-than-1.0.12), the `subkey_len`(uint64_t) of `sodium_crypto_kdf_derive_from_key` accept any value up to (2^64)-1.

However, in `libsodium-php`, it's only possible to use `subkey_len` up to (2^63)-1, due to this negative check:

https://github.com/jedisct1/libsodium-php/blob/ad1b26280b0d60b6e90a198e83d5dfde14a5b6e1/libsodium.c#L3761-L3764

I tried to remove this check in my version, and compare with the key generated by other programs in C. I can confirm that keys with subkey_id >= 2^63 can be correctly generated in `libsodium-php`.

I think this check needs to be removed, or a mechanism to pass in numbers up to (2^64)-1 needs to be provided to ensure its behavior is consistent with libsodium.

**Comment by jedisct1** [comment]
PHP doesn't support unsigned integers, so you would actually be passing a negative value, or trigger an undefined behavior.

The check is intentionally here to avoid such inconsistencies.

The key identifier is meant to be a counter, in case multiple keys have to be derived. Deriving more than 2^63 keys is not really practical.

**Comment by Coxxs** [comment]
Guess I have to blame the vendor for using random uint64 as the `subkey_id` :(
