### ISSUE TITLE
Compatibility issue

### ISSUE THREAD

**Issue by contreraslinoti** [jedisct1/libsodium-php#226]
Hi there, 
`sudo pecl install -f libsodium` issues to a sodium extension not compatible with php 8.1.x 
I'm not able to compile from sources since configure file miss from libsodium-php sources, could you provide it please?
![Sélection_043](https://user-images.githubusercontent.com/82545629/182771038-61305cf6-61f2-4144-8396-df5d1c483155.png)

**Comment by jedisct1** [comment]
The libsodium extension is already part of PHP 81. You don't need to use PECL.
