### ISSUE TITLE
Issue using sodium in PHP 7.3 SODIUM_CRYPTO_AEAD_AES256GCM_KEYBYTES global variable in M1 

### ISSUE THREAD

**Issue by jtirado1996** [jedisct1/libsodium-php#227]
I'm getting this error when I try to use composer install in my project
I'm using macOS Monterey with an Apple chip M1 with PHP7.3 using Laravel 7

![image](https://user-images.githubusercontent.com/114944610/194768610-489103c2-eee7-48e2-a058-a8cb870c0956.png)

**Comment by jedisct1** [comment]
![Uploading Screenshot 2022-10-09 at 22.52.56.png…]()
