### ISSUE TITLE
HHVM Support

### ISSUE THREAD

**Issue by cmckni3** [jedisct1/libsodium-php#24]
Any chance of supporting [HHVM](http://hhvm.com)?

I am just curious right now if I ever decide to start using HHVM. The [extension API wiki](https://github.com/facebook/hhvm/wiki/Extension-API) is pretty detailed with instructions and examples of creating an HHVM extension.

**Comment by cmbankester** [comment]
Bump. Would like to know if HHVM support is planned.

**Comment by jedisct1** [comment]
Not really, due to a lack of spare time. But pull requests are always welcome :)

**Comment by drbo** [comment]
I believe that HHVM can run Zend extensions, though this is not enabled by default.

**Comment by cmckni3** [comment]
Being added to PHP 7.2 at https://github.com/php/php-src/pull/2560 and HHVM at https://github.com/facebook/hhvm/releases/tag/HHVM-3.20.0
