### ISSUE TITLE
Installation: several bugs in the documentation

### ISSUE THREAD

**Issue by eriksank** [jedisct1/libsodium-php#27]
**Problem number one.** This will not work in Ubuntu:

            apt-get install libsodium  #WRONG

For the one or the other reason totally unknown to me, it has to be:

            apt-get install libsodium13

**Problem number two.** Even though I do not fully understand all the details embedded in the file `config.m4`, it is patently clear that it searches for the libsodium header files and if it cannot find them, it will conclude that libsodium is not installed. Therefore, you must first install `libsodium-dev`, before trying to install the php extension with `pecl`:

           apt-get install libsodium-dev

**Problem number three.** The following instruction will spectacularly fail:

          sudo pecl install libsodium #WRONG

It has to be done like this:

          sudo pecl install libsodium-beta

There are numerous bugs in the documentation. I think that quite a few users will never manage to install this php extension, just because of these bugs ...

**Comment by jedisct1** [comment]
Fixed, thanks!

**Comment by bitbeans** [comment]
Install libsodium-1.0.2 and PECL libsodium on Ubuntu 14.04
https://gist.github.com/sarciszewski/f03aae0b4c521c138b94

The version is outdated but the script still works :)
