### ISSUE TITLE
crypto_aead_chacha20poly1305_decrypt triggers E_ERROR when decryption / authentication fails

### ISSUE THREAD

**Issue by leonklingele** [jedisct1/libsodium-php#35]
.. that's why I created #33 

See this gist for what went wrong: https://gist.github.com/leonklingele/982e79ad34704f8651c9

TL;DR:
When `crypto_aead_chacha20poly1305_decrypt` is unable to decrypt & authenticate, it triggers an E_ERROR.
E_ERROR errors can't be handled and the whole script instantly terminates. That's bad.
https://github.com/jedisct1/libsodium-php/blob/77095ed6850426b02deecc3f8431236e92f043b1/libsodium.c#L1288

`crypto_aead_chacha20poly1305_decrypt` should return false instead if an error occurs, so we can handle it.

**Comment by thebigb** [comment]
I agree on this one. This should be an exception.

**Comment by jedisct1** [comment]
That was fixed in 824ec20022f16f28529b24aafe6859bf8c638125

**Comment by leonklingele** [comment]
Awesome. That was fast.
Can you please push a new release some time soon?
