### ISSUE TITLE
Do not trigger E_ERRORs at all.

### ISSUE THREAD

**Issue by leonklingele** [jedisct1/libsodium-php#37]
Do not trigger E_ERRORs. Always return false instead.
All errors, if possible, should be treatable.
Especially look at those within encryption / decryption functions. They __must__ be treatable.

Examples:
  1. https://github.com/jedisct1/libsodium-php/blob/824ec20022f16f28529b24aafe6859bf8c638125/libsodium.c#L1473
  2. https://github.com/jedisct1/libsodium-php/blob/824ec20022f16f28529b24aafe6859bf8c638125/libsodium.c#L1485
  3. https://github.com/jedisct1/libsodium-php/blob/824ec20022f16f28529b24aafe6859bf8c638125/libsodium.c#L450
  4. https://github.com/jedisct1/libsodium-php/blob/824ec20022f16f28529b24aafe6859bf8c638125/libsodium.c#L457
  5. ..

**Comment by jedisct1** [comment]
Strongly disagree here.

These errors only happen if the API is used incorrectly, and ignoring them can have catastrophic implications. Ignoring them shouldn't be possible.

**Comment by leonklingele** [comment]
No. Not all of them.

Look at:
  1. https://github.com/jedisct1/libsodium-php/blob/824ec20022f16f28529b24aafe6859bf8c638125/libsodium.c#L457
  2. https://github.com/jedisct1/libsodium-php/blob/824ec20022f16f28529b24aafe6859bf8c638125/libsodium.c#L537
  3. https://github.com/jedisct1/libsodium-php/blob/824ec20022f16f28529b24aafe6859bf8c638125/libsodium.c#L797
They're the same as #35

**Comment by jedisct1** [comment]
These should never fail, unless there is an internal error in Sodium or in the way the extension uses them.

**Comment by leonklingele** [comment]
OK. Guess I was a bit overeager when I opened this. Sorry for that. :-1:
