### ISSUE TITLE
New release coming soon?

### ISSUE THREAD

**Issue by leonklingele** [jedisct1/libsodium-php#38]
It would be great if you could push a new release. Two major changes were made since v1.0.3:

  - Introduction of \Sodium namespace, current release isn't compatible with examples in readme: https://github.com/jedisct1/libsodium-php/commit/7b5d819e2f35953ea46a8bc360341177cf90dd50
  - ChaCha20Poly1305 decryption broken: https://github.com/jedisct1/libsodium-php/commit/824ec20022f16f28529b24aafe6859bf8c638125

That would be awesome. Thank you in advance for your efforts.

**Comment by paragonie-scott** [comment]
It looks like [this is coming very soon](https://twitter.com/jedisct1/status/624698709864001536).

**Comment by jedisct1** [comment]
Released :)

**Comment by leonklingele** [comment]
:dancers:
