### ISSUE TITLE
Expose crypto_scalarmult_base and/or base point constant.

### ISSUE THREAD

**Issue by bantu** [jedisct1/libsodium-php#39]
Please expose the `crypto_scalarmult_base` function and/or the curve25519 base point as a constant. Otherwise `crypto_scalarmult` has to be used with the base point manually supplied as `"\x09" . str_repeat("\00", 31)` (as per http://cr.yp.to/ecdh.html) when performing ECDH.

**Comment by jedisct1** [comment]
It's already there :)

But called `\Sodium\crypto_box_publickey_from_secretkey()`.

**Comment by bantu** [comment]
Indeed. Thanks. I wonder what the difference between crypto_box_publickey_from_secretkey and crypto_scalarmult_base is then. Looking.

**Comment by jedisct1** [comment]
None!

This function was exposed as `crypto_box_publickey_from_secretkey()` for clarity, as this is its typical use case, and intuitively, many people don't know what `crypto_scalarmult_base()` is for, and how it relates to `crypto_box_*`.

**Comment by bantu** [comment]
I think whether that makes sense largely depends on what perspective a user has. It's probably a very hard decision to make.

libsodium(-php) caters well to the use case where it communicates with another instance of libsodium. It very well hides all the underlying crypto algorithms. However, in my specific case I am trying to make PHP code compatible with software using curve25519 for ECDH. Additionally, I also understand the underlying mathematical operations.
I find it very confusing that there is no `crypto_scalarmult_base` function (libsodium-php issue only I think), but also find it confusing that there is no mention of curve25519 in any of the function names (generic libsodium problem).

I'd probably recommend NOT having `crypto_box_publickey_from_secretkey`, unless there is an equivalent function in libsodium. Otherwise this just unnecessarily adds even more confusion.

**Comment by jedisct1** [comment]
There is `crypto_scalarmult_base()` now, as an alias.

**Comment by bantu** [comment]
Thanks.
