### ISSUE TITLE
0.2.0 archive is broken

### ISSUE THREAD

**Issue by remicollet** [jedisct1/libsodium-php#40]
At least compat.h is missing.

**Comment by jedisct1** [comment]
I know. Something goes wrong every single time I try to use PECL.

It's not broken in git, but the package.xml was missing this file when the package was uploaded to PECL.

Is there a way to update the 0.2.0 version on PECL or do I have to release 0.2.1?

**Comment by remicollet** [comment]
From pecl.php.net you can "remove"  the release and upload it again.

Notice this is a bad practice, which is "acceptable" if done in a very short time.

**Comment by jedisct1** [comment]
I've been looking for the "remove" button to no avail.
OK, let's tag a 0.2.1 version, then.

**Comment by remicollet** [comment]
I have edit my previous comment ;)

**Comment by jedisct1** [comment]
Wow. The pen. That was well hidden. Thanks for the tip!
