### ISSUE TITLE
0.2.0 is broken with 5.6

### ISSUE THREAD

**Issue by remicollet** [jedisct1/libsodium-php#41]
PHP Warning:  PHP Startup: Unable to load dynamic library '/dev/shm/BUILDROOT/php-pecl-libsodium-0.2.0-1.fc21.remi.5.6.x86_64/usr/lib64/php/modules/libsodium.so' - /dev/shm/BUILDROOT/php-pecl-libsodium-0.2.0-1.fc21.remi.5.6.x86_64/usr/lib64/php/modules/libsodium.so: undefined symbol: zend_error_noreturn in Unknown on line 0

**Comment by jedisct1** [comment]
Awww crap. I give up for today.

**Comment by jedisct1** [comment]
It seems to work as expected on OSX, OpenBSD, Ubuntu and on a dead old Debian with PHP 5.4.
So it might be specific to Fedora not exporting this symbol. Not sure what to do here.

**Comment by remicollet** [comment]
Be aware that standard PHP use RTLD_LAZY, which means that undefined symbol are not resolved at load time (but later, when used)

On Fedora we use RTLD_NOW, so segfault occurs immediately, at load time.

**Comment by jedisct1** [comment]
But the test suite is running fine on these systems.

Looks like a common, Fedora-specific issue and the workaround is apparently to replace `zend_error_noreturn()` with `zend_error()`. Did that. Lemme know if it works for you.

**Comment by remicollet** [comment]
After fixing the **zend_error_** to **zend_error** issue

Tested with :
* libsodium 1.0.3
* Fedora 19, 20, 21, 22
* RHEL 6, 7
* i386 + x86_64
* NTS and ZTS
* php 5.4.43, 5.5.27, 5.6.11, 7.0.0beta2

All build + load + test suite are ok.

**Comment by jedisct1** [comment]
Fantastic!

Thanks again for your invaluable help, Remy!

**Comment by remicollet** [comment]
Just FYI, on 5.6.11/Zend/zend.h you have:

    void zend_error_noreturn(int type, const char *format, ...) __attribute__ ((noreturn));

in 7.0.0beta2/Zend/zend.h:

     ZEND_API ZEND_NORETURN void zend_error_noreturn(int type, const char *format, ...);

So zend_error_noreturn is part of public API only in PHP  7+
