### ISSUE TITLE
Prebuild Windows DLLs

### ISSUE THREAD

**Issue by rugk** [jedisct1/libsodium-php#46]
In https://pecl.php.net/package/libsodium or http://windows.php.net/downloads/pecl/releases/libsodium/ I can't find any prebuild Windows DLLs.
Interestingly in http://windows.php.net/downloads/pecl/releases/libsodium/ there seem to be even build logs, but no actual DLL is there.

So it would be nice if you could provide pre-compiled DLLs there.

Related: Build instructions: https://github.com/jedisct1/libsodium-php/issues/8 by @Screeze

**Comment by rugk** [comment]
@Jan-E you maybe have some prebuild DLLs because of https://github.com/jedisct1/libsodium-php/pull/26.

**Comment by Jan-E** [comment]
There is a libsodium.dll in all my builds at
https://www.apachelounge.com/viewtopic.php?t=6359

Or for PHP7 at
https://www.apachelounge.com/viewtopic.php?t=6617

**Comment by rugk** [comment]
Okay, sounds great. Although you of course only need the php_libsodium.dll (and the other libsodium.dll) for the libsodium PECL package.
So who can put these to https://pecl.php.net/package/libsodium so other users can download it?

**Comment by Jan-E** [comment]
The maintainers of the Windows PHP server should do that:
http://windows.php.net/team/

**Comment by rugk** [comment]
Has someone any contact to them?
I think at least @jedisct1 should have.

**Comment by Master-Antonio** [comment]
Yes in fact.

**Comment by rugk** [comment]
@Master-Antonio
Do you have contact or do you just confirm that @jedisct1 has any contact to them?
In the latter case do you can inform @jedisct1 as he does not seem to react on this mentions here.

Or does anyone else can contact the [team](http://windows.php.net/team/)?

**Comment by Master-Antonio** [comment]
I just confirm that what @Jan-E said .

**Comment by jedisct1** [comment]
I've never used PHP on Windows,, so it would be probably better if someone whose more familiar with this environment got in touch with the right people :)

**Comment by padraigdoran** [comment]
Hi all,

I found that the currently available php_libsodium.dll (version 1.0.6) is compiled with libsodium headers 1.0.5 so functions like \Sodium\crypto_pwhash_str() are not available.

I've built libsodium.dll as 1.0.9 and I've built php_libsodium.dll  against the 1.0.9 headers.

libsodium compiled version: 1.0.6
libsodium headers version: 1.0.9
libsodium library version: 1.0.9

It's compiled as VC11 x64:

| Build type      | Release                  |
| Thread Safety   | No                       |
| Compiler        | MSVC11 (Visual C++ 2012) |
| Architecture    | x64                      |
| Optimization    | PGO disabled             |
| Static analyzer | disabled                 |


This is the download link:
https://www.dropbox.com/s/jxabcsv9zovnnbf/php_libsodium_106_libsodium_109.zip?dl=0

**Comment by Jan-E** [comment]
Did you have to add crypto_pwhash.c to the vcxproj? Like this:

![capture](https://cloud.githubusercontent.com/assets/1757825/17066965/cb548fa6-5049-11e6-9d5d-4da20d9f763b.PNG)

**Comment by Jan-E** [comment]
A, right. That was https://github.com/jedisct1/libsodium/commit/3fe5590b944cb6455596c84faeaf5854faf1b0c5

**Comment by Jan-E** [comment]
I have recompiled all my builds of PHP 5.3, 5.4, 5.5, 5.6 & 7.0 against the git head of https://github.com/jedisct1/libsodium

This gives a strange combination of versions, but they are as up-to-date as can be.

libsodium support: enabled
libsodium compiled version: 1.0.6
libsodium headers version: 1.0.10
libsodium library version: 1.0.11

Downloads: https://www.apachelounge.com/viewtopic.php?t=6359

**Comment by padraigdoran** [comment]
That's great @Jan-E thanks for the ongoing work and contributions!

**Comment by Jan-E** [comment]
BTW I did the same for PHP 7.1.0 beta 1:
https://www.apachelounge.com/viewtopic.php?t=6617

**Comment by padraigdoran** [comment]
@Jan-E - I see a release of Libsodium 1.0.11 from 3 days ago (https://github.com/jedisct1/libsodium/releases/tag/1.0.11) You have compiled php_libsodium against the 1.0.10 headers. Could you compile them with the 1.0.11 headers please. Specifically for php 7.0 nts VC14 x64

Thanks.

**Comment by Jan-E** [comment]
I had already recompiled the PHP7 x86 versions, but the X64 ones not yet. X64 nts is there as well now. X64 ts will follow.

@jedisct1 Do not forget to ping @weltling at a new release of libsodium lib. http://windows.php.net/downloads/pecl/releases/libsodium/1.0.6/ does not seem up-to-date yet.
