### ISSUE TITLE
PHP 7 + \Sodium\memzero()

### ISSUE THREAD

**Issue by paragonie-scott** [jedisct1/libsodium-php#58]
Compare the behavior of this snippet on PHP 5.* versus 7.0.0-RC5

    <?php
    class Foo {
        public $x;
        public function __construct($x) {
            $this->x = $x;
        }
    }
    $var = \Sodium\randombytes_buf(32);
    $y = new Foo($var);
    \Sodium\memzero($var);
    var_dump(\Sodium\bin2hex($y->x));

On PHP 7, I get this:

     string(64) "0000000000000000000000000000000000000000000000000000000000000000"

What's really going on here? PHP 7 internally passes strings by reference, not by value, as an optimization strategy, since in PHP userland code C-strings are essentially immutable. Overwriting memory in one place leads to it being overwritten in two places unless you coerce it to a cast.

Now change the snippet to:

    <?php
    class Foo {
        public $x;
        public function __construct($x) {
            $this->x = '' . $x;
        }
    }
    $var = \Sodium\randombytes_buf(32);
    $y = new Foo($var);
    \Sodium\memzero($var);
    var_dump(\Sodium\bin2hex($y->x));

A single run gives me this output:

    string(64) "8a8be57b96445030684852d75b267d40179be00c1b26b603c23bb6927104ce50"

Solution: Even after running headfirst into this, I don't think this is a bug in PHP or in libsodium. This behavior just needs to be documented (which I'll work on today).

**Comment by paragonie-scott** [comment]
```php
$str = 'stdclass';
\Sodium\memzero($str);
$obj = json_decode(json_encode(['foo' => 'bar']));
var_dump($obj);
```
Output:

    object()#1 (1) {
      ["foo"]=>
      string(3) "bar"
    }

**Comment by jedisct1** [comment]
df840bcf46b6b361f5b458a79669daa4355cb5c6 may fix this.

I'd still love some input from someone more familiar with the PHP internals.

**Comment by paragonie-scott** [comment]
For the test case: switch `stdclass` with `stdClass`; I made a typo in my original comment.

**Comment by jedisct1** [comment]
It does matter. And it shows that the fix is insufficient :(

**Comment by nikic** [comment]
@jedisct1 The check should be for `Z_REFCOUNT(*buf_zv) > 1` instead. Probably also want to still do the `convert_to_null(buf_zv)` in that case.

**Comment by jedisct1** [comment]
I've never seen the refcount being `< 2` here. Does `zend_parse_parameters()` increase the reference count?

**Comment by nikic** [comment]
@jedisct1 Ah sorry, I didn't look closely enough. The check also has to be moved after the DEREF.

**Comment by nikic** [comment]
Before the DEREF the refcount is how many "variables" are part of the reference set. After the DEREF the refcount is the number of users of the value (including one for the reference set).

**Comment by jedisct1** [comment]
289228e24c954546c34ba1b68cdcf78ed3e84983 ?

**Comment by nikic** [comment]
Looks good to me

**Comment by jedisct1** [comment]
@paragonie-scott Can you check that these issues are fixed? Including the `sodium_increment()` issue?

**Comment by paragonie-scott** [comment]
Yep, the fix works.

![confirmed fix](https://cloud.githubusercontent.com/assets/11591518/10672763/01e77fcc-78c0-11e5-9f04-95b5ec918078.png)

**Comment by jedisct1** [comment]
Thanks a lot for your help, Scott !

**Comment by paragonie-scott** [comment]
@jedisct1 Any time. :)

@nikic Thanks for sharing your insight of PHP's internals :+1:
