### ISSUE TITLE
Build results in uncallable methods

### ISSUE THREAD

**Issue by cinnion** [jedisct1/libsodium-php#65]
When building on a CentOS 6 machine with a PHP 5.3.3 install, the functions are not callable.  A call such as \Sodium\library_version_major() in the test script of the install instructions (with the '[' replaced with the PHP 5.3.3 array syntax) results in the following:

    PHP Fatal error:  Call to undefined function Sodium\library_version_major() in /tmp/libsodium-test.php on line 3
    PHP Stack trace:
    PHP   1. {main}() /tmp/libsodium-test.php:0

When checking, get_extension_funcs() returns an array with mangled names, which lead to the discovery that calls could be made with constructs such as

    call_user_func('\Sodium\\"library_version_major"");

instead.

"php --version" gives:
    PHP 5.3.3 (cli) (built: Jul 12 2013 20:35:47) 
    Copyright (c) 1997-2010 The PHP Group
    Zend Engine v2.3.0, Copyright (c) 1998-2010 Zend Technologies

This is version 1.0.2 of the pecl package, and was installed using 'pecl install libsodium'

**Comment by jedisct1** [comment]
PHP 5.3.x is not supported and will not be supported. 

The PHP developers stopped supporting this branch a long time ago, and PHP 5.4.x also reached EOL. They won't even get any security updates any more.

Can you try again with a current version of PHP ?

**Comment by cinnion** [comment]
Then the PECL page at https://pecl.php.net/package/libsodium needs to be updated to indicate that the minimum version supported is 5.4.x, or whatever.

As for using PHP 5.4.x, it is a very large legacy application which still requires 5.3.x, and to make matters worse, RHEL 6 is still using PHP 5.3 by default (a totally different issue).

**Comment by paragonie-scott** [comment]
Is there a 5.4 package avialable in RHEL? What features does your legacy application require from 5.3 that are not available in 5.4?

**Comment by cinnion** [comment]
RHEL/CentOS (and likely the equivilent OEL) still have PHP 5.3, for both RHEL5 and RHEL6, but nothing newer without building it custom.  The legacy application is quite large, and still makes use of things like call-time pass-by-reference and functions which are no longer available with 5.4, just for starters.  That is being worked on, but resource constraints and all...  for right now, we will just have to make due with wrapping the function calls we will use with call_user_func()/call_user_func_array().
