### ISSUE TITLE
Minor issue in utils.phpt

### ISSUE THREAD

**Issue by thebigb** [jedisct1/libsodium-php#66]
The line `$obj = json_decode(json_encode(['foo' => 'bar']));` in [utils.phpt](https://github.com/jedisct1/libsodium-php/blame/master/tests/utils.phpt#L39) triggers an error on my systems, mentioning that `json_encode()` and `json_decode()` are undefined. This is likely because I'm running Debian, which requires a *free* implementation to be loaded from an extension. I'm guessing that the test script sets up a clean environment and doesn't test with loaded extensions on the system.

I can easily ignore the issue, but looking at the code, I'm not even sure why it's there. Can it be safely removed, or does it have a specific purpose?

**Comment by jedisct1** [comment]
That test was required in order to check that it wasn't possible to override things such as `stdClass` on PHP7.

@paragonie-scott If JSON is not available, what else could we possibly use in order to trigger the same issue?

**Comment by paragonie-scott** [comment]
Perhaps...

    $obj = unserialize("O:8:"stdClass":1:{s:3:"foo";s:3:"bar";}");

...would be a better candidate?

**Comment by thebigb** [comment]
Out of sheer curiosity, why not just `$obj = (object)['foo' => 'bar']`?

**Comment by paragonie-scott** [comment]
https://3v4l.org/DKELf

You're right. I forgot you could typecast to `(object)` that way.

**Comment by jedisct1** [comment]
Let's try than, then :)

**Comment by jedisct1** [comment]
Should be fixed in cad301b53e9a783e0ed69e8acb4bbfd2922a6909 :)
