### ISSUE TITLE
Typo in install instructions

### ISSUE THREAD

**Issue by desertdev** [jedisct1/libsodium-php#67]
In the install instructions here: https://paragonie.com/book/pecl-libsodium/read/00-intro.md#installing-libsodium

"install" is "intsall" in this line:

sudo apt-get update && sudo apt-get intsall libsodium-dev

**Comment by paragonie-scott** [comment]
Thanks, this is corrected in https://github.com/paragonie/pecl-libsodium-doc/commit/a761a21ffabeddd98f505cf35ba38c870956fb05 :)

**Comment by jedisct1** [comment]
Thanks!
