### ISSUE TITLE
Composer.json to publish it on packagist.org

### ISSUE THREAD

**Issue by rugk** [jedisct1/libsodium-php#68]
It would be nice if you could add a `composer.json` and publish it on [packagist.org](https://packagist.org).

**Comment by paragonie-scott** [comment]
How do you propose we distribute a PHP extension that has to be compiled on your system through Composer?

**Comment by rugk** [comment]
Well... don't know.
I was more about the dependencies of this extension as it requires libsodium.
Or is it automatically checked when installing this extension that libsodium is installed and if not that it is installed.

**Comment by paragonie-scott** [comment]
If you need to add libsodium as a dependency for your project, you can do it like so:

https://github.com/paragonie/halite/blob/4cd2debc6dd2bd9ca3e87374750fa60c67f8d712/composer.json#L7

**Comment by rugk** [comment]
Thanks for the example.
So this makes sure that both libsodium-php and the libsodium library are installed?

**Comment by paragonie-scott** [comment]
Sort of.

If you install both then uninstall the underlying library without removing the PHP extension, you can bork your PHP project. Why anyone would go out of their way to do that, I don't know.

Maybe propose a feature so Composer can detect system libraries?

**Comment by rugk** [comment]
Done in https://github.com/composer/composer/issues/4598

**Comment by rugk** [comment]
As https://github.com/composer/composer/issues/4598 was closed closing this.
