### ISSUE TITLE
PHP stubs for IDEs

### ISSUE THREAD

**Issue by thebigb** [jedisct1/libsodium-php#77]
It would be nice to have documented stubs of this extension's functions.

I imagine there'd be tools to generate them, but my Google-fu is weak on this one.

**Comment by paragonie-scott** [comment]
@GeeH Is this something that could be done for PHPStorm?

**Comment by GeeH** [comment]
I'm sorry I'm not aware of this project, can you elaborate pleas?

**Comment by paragonie-scott** [comment]
This is a PHP extension in PECL that provides a bunch of functions in the `Sodium` namespace. 

* Documentation: https://paragonie.com/book/pecl-libsodium
* Example: https://github.com/paragonie/halite/blob/4f90faa6468790f1af273bfa3f45a12be9e35c6a/src/Password.php#L28-L32

Is there any way to make PHPStorm cooperate with this optional PHP extension? i.e.

1. Detect that the extension is loaded.
2. If it is loaded, provide hints based on the version installed.

Don't worry about the specifics of what this extension does; I can help make it happen from that side of things.

**Comment by GeeH** [comment]
It's unlikely that any detection for the extension would be done, we don't do that for any extensions at the moment.

However, to get code completion for the extension, you can simply create a PR to the stubs project here:

https://github.com/JetBrains/phpstorm-stubs

G

**Comment by GeeH** [comment]
NOTE: Your PR may not be accepted if the extension is not popular, we're working on an additional way to provide code completion currently.

**Comment by paragonie-scott** [comment]
Thanks for the information. :)

**Comment by paragonie-scott** [comment]
https://github.com/paragonie/halite/blob/master/stub/Sodium.stub.php

Just having that somewhere in my project directory seems to trick phpstorm into not highlighting `Sodium` in red any more. :)

**Comment by olemartinorg** [comment]
Hate to be that guy, but +1. I didn't see a pull request for this at https://github.com/JetBrains/phpstorm-stubs yet. @paragonie-scott, did you submit one? I just googled "libsodium phpstorm" and luckily ended up here. (Thanks for the stub!)

**Comment by merlingore** [comment]
Thanks for submitting this @paragonie-scott.

**Comment by fredemmott** [comment]
FYI, hphp/hack/hhi/ext_libsodium.hhi from https://github.com/facebook/hhvm/commit/044a06d4ea10ec32283ab7f8efce8d860a078318 mostly gets you up-to-date stubs. Given that's meant for the hack typechecker, there's two shortcomings with it:

 - anything taken by reference is typed as `mixed`
 - anything that returns `false|SomeType` is typed as returning `mixed`
