### ISSUE TITLE
Are there any disadvantages of using bin2hex/hex2bin of this library instead of the native ones?

### ISSUE THREAD

**Issue by rugk** [jedisct1/libsodium-php#78]
I saw you offer time-safe replacements for PHPs `bin2hex` and `hex2bin`. As we use [bin2hex](https://github.com/rugk/threema-msgapi-sdk-php/search?utf8=%E2%9C%93&q=bin2hex&type=Code) and [hex2bin](https://github.com/rugk/threema-msgapi-sdk-php/search?utf8=%E2%9C%93&q=hex2bin&type=Code) quite often in the library (which uses libsodium and therefore does cryptographically things) I thought that using libsodiums implementation instead of the native PHP one might be a good thing to do.

But before doing this I of course want to be sure this has no negative effects and that's why I am asking whether there are any disadvantages of doing so.

In case you want to get some reputation you can also [answer this question on StackExchange](https://crypto.stackexchange.com/questions/31930/are-there-any-disadvantages-of-using-libsodiums-helpers-for-en-decoding-compari).

**Comment by paragonie-scott** [comment]
PHP's implementation of `bin2hex()` and `hex2bin()` were not designed in accordance to [cryptography coding standards](https://cryptocoding.net/index.php/Coding_rules#Avoid_table_look-ups_indexed_by_secret_data).

Use the libsodium ones until I can convince PHP internals to do the right thing with cache-timing safety.

**Comment by jedisct1** [comment]
There is nothing wrong in using the Sodium version of these instead of the built-in ones, even when not comparing secrets. They might just be imperceptibility slower.

`sodium_hex2bin()` is also more convenient than the built-in one when separators can be present.

**Comment by rugk** [comment]
Thanks for these information. [I've changed it](https://github.com/rugk/threema-msgapi-sdk-php/pull/33).
