### ISSUE TITLE
\Sodium\version_string not avaliable

### ISSUE THREAD

**Issue by rugk** [jedisct1/libsodium-php#79]
php -i | grep sodium

Results:

    libsodium
    libsodium support => enabled
    libsodium headers version => 1.0.8
    libsodium library version => 1.0.8

----

[This script](https://gist.github.com/rugk/eae69ad07042a1d51d57) returns:
```
libsodium is loaded
you use a recent version of libsodium
Fatal error: Call to undefined function Sodium\version_string() in /home/testscript/check.php on line 15
```

more information here: https://github.com/rugk/threema-msgapi-sdk-php/issues/31
error report by @medienverbinder

**Comment by medienverbinder** [comment]
Issue Solved.

more : https://github.com/rugk/threema-msgapi-sdk-php/issues/31#issuecomment-172191651
