### ISSUE TITLE
How to get the version number of libsodium-php?

### ISSUE THREAD

**Issue by rugk** [jedisct1/libsodium-php#80]
With `\Sodium\version_string()` I can get the version number of [libsodium](https://github.com/jedisct1/libsodium), but is there any way to get the version number of libsodium-php?

**Comment by cmckni3** [comment]
It would be nice if the version showed up when calling `phpinfo` and when running `php -i`

**Comment by cmckni3** [comment]
You can get the version by running the following PHP code.

```php
$ext = new ReflectionExtension('libsodium');
var_dump($ext->getVersion());
```

**Comment by Eddcapone** [comment]
I get 500 server error.

**Comment by jedisct1** [comment]
That's a configuration error in your web server; it has nothing to do with libsodium.

**Comment by Eddcapone** [comment]
I mean after executing the script

```
$ext = new ReflectionExtension('libsodium');
var_dump($ext->getVersion());
```
