### ISSUE TITLE
tests/utils.phpt fail under php 5.5.31 when using "static" string

### ISSUE THREAD

**Issue by glensc** [jedisct1/libsodium-php#82]
after applying patch from #81

btw, i found something rather weird and disturbing when running this under php 5.5.31, other versions (5.3, 5.4, 5.6, 7.0 work fine)

``` diff
➔ cat tests/utils.diff
004- string(22) "0000810102030405060708"
004+ string(22) "ffff800102030405060708"
006- int(0)
006+ int(-1)
007- int(1)
007+ int(-1)
```

my php is very basic modules, so no opcachers etc:

```
$ php55 -m
[PHP Modules]
Core
date
ereg
json
libxml
pcre
Reflection
standard

[Zend Modules]

$ php55 -v
PHP 5.5.31 (cli) (built: Jan 11 2016 00:05:16) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
```

i added `var_dump(hex2bin('FFFF800102030405060708') == "\xFF\xFF\x80\x01\x02\x03\x04\x05\x06\x07\x08"));` under that php, and it returned `true`, so it's not encode issue

looks like some internal memory getting overwritten or something...

so, i changed the test to not contain "static string" but something that's "dynamically built" like you had before (function return value):

```
$v = ""."\xFF\xFF\x80\x01\x02\x03\x04\x05\x06\x07\x08";
```

now the test passed!

what you think of this? i can create PR with the "fix", but i think this should be investigated first!
can you reproduce this on your system with php 5.5?

**Comment by paragonie-scott** [comment]
This looks very similar to #58.

**Comment by glensc** [comment]
note that problem is visible with 5.5 series only

**Comment by glensc** [comment]
could be that the problem is that in php5.5 the string is immutable?

https://github.com/jedisct1/libsodium-php/blob/1.0.2/libsodium.c#L427-L429

imho it's wrong for the increment function to skip increment silently, should throw exception!

**Comment by glensc** [comment]
i also don't understand the test committed as 289228e24c954546c34ba1b68cdcf78ed3e84983

he does `memzero` on `$str`, but never prints it out, thus it's not actually "tested"!

```php
$str = 'stdClass';
\Sodium\memzero($str);
```

**Comment by jedisct1** [comment]
The test committed as 289228e refers to https://github.com/jedisct1/libsodium-php/issues/58#issuecomment-150026707

Yes, zeroing strings in PHP is a mess.

**Comment by glensc** [comment]
@jedisct1 i mean that test doesn't test anything, to able to test what is result, you should `var_dump` it.

**Comment by jedisct1** [comment]
It does. It checks that `stdClass` was not renamed. The 4 last lines are a single test.
