### ISSUE TITLE
Latest version on PECL is 1.0.2 - can't install from newly compiled .tar.gz

### ISSUE THREAD

**Issue by DJDavid98** [jedisct1/libsodium-php#85]
I can't get PECL to install the newly compiled 1.0.8 package. I get the following after running everything except `sudo make install` ([using this guide](https://paragonie.com/book/pecl-libsodium/read/00-intro.md#installing-libsodium)):
```
$ pecl install libsodium-1.0.8.tar.gz
parsePackageName(): "1.0.8.tar.gz" is neither a valid version nor a valid state in "libsodium-1.0.8.tar.gz"
could not extract the package.xml file from "libsodium-1.0.8.tar.gz"
install failed
```

I'm on Debian wheezy with latest `php5-fpm` & `php5-cli`. The build succeeded, and previously I also tried running `sudo make install`, but when I'm instructed to "run `pecl uninstall libsodium` and `pecl install libsodium`", it just installs 1.0.2 again, ignoring the built package. The version check gives me
```
$ php ~/version_check.php
array(2) {
  [0]=>
  int(7)
  [1]=>
  int(5)
}
```

which is obviously lower than what's on the site I linked.  Specifying the path to the newly made `/usr/local/lib/libsodium.so` (created by `sudo make install`) in `php.ini` just gives me

```
$ php ~/version_check.php
PHP Warning:  PHP Startup: Invalid library (maybe not a PHP library) '/usr/local/lib/libsodium.so' in Unknown on line 0
PHP Fatal error:  Call to undefined function Sodium\library_version_major() in /root/version_check.php on line 3
```
I'd prefer to use the latest version, but I can't seem to get it to work.

**Comment by paragonie-scott** [comment]
> `pecl install libsodium-1.0.8.tar.gz`

Try just `pecl install libsodium`. Version 1.0.2 is the latest version of the PECL extension, while version 1.0.8 is the latest version of the library.

[They're separate](https://paragonie.com/book/pecl-libsodium/read/00-intro.md#installing-libsodium).

**Comment by DJDavid98** [comment]
The page says

>If you get different numbers, you won't have access to some of the features that should be in libsodium 1.0.4

I'm getting `7` and `5`, and not `7` and `6`.

**Comment by paragonie-scott** [comment]
1. Compile libsodium as per the instructions at the bottom of the page.
2. Install the PHP extension via PECL (just `pecl install libsodium` without any `-verison` or `.tar.gz`)

Sorry that your package maintainers aren't providing 1.0.8

**Comment by DJDavid98** [comment]
I _did_ compile it, at least 4 times already. No matter how many times I went through the process from start to finish, nothing changed, and the version output by the test script remained `7` and `5`.

**Comment by paragonie-scott** [comment]
Oh, I see. Try this, maybe?

    pecl uninstall libsodium
    pecl install libsodium

I remember running into this problem a while back, but that was on a borked VM, so I don't know if the solution that worked for me is applicable to the one you're encountering.

**Comment by DJDavid98** [comment]
I ran these 2 countless times already, but just to make sure, I ran them again. No change in the version numbers whatsoever. PECL still installs `libsodium-1.0.2` and the script returns the same numbers as before.

**Comment by paragonie-scott** [comment]
It may help to get rid of any distro-provided binaries, e.g. `apt-get purge libsodium1.*`

**Comment by paragonie-scott** [comment]
Note: PECL installing `libsodium-1.0.2` is the **correct** outcome. PECL 1.0.2 is the latest. PECL libsodium and the underlying libsodium are separate. You need the latest underlying library then to reinstall PECL once you're sure you have 1.0.8.

**Comment by DJDavid98** [comment]
I've removed the distro-provided ones and going to do a rebuild then, will reply with the results later

**Comment by DJDavid98** [comment]
Indeed, the distro-provided packages were the culprit. I've re-compiled everything and the numbers jumped to `9` and `1`. I highly suggest adding that line (`apt-get purge libsodium1.*`) or a hint about removing old packages previously installed by `apt-get` to that page somewhere.

**Comment by paragonie-scott** [comment]
Will do. Sorry for not preventing the time you burned on this.

**Comment by DJDavid98** [comment]
No problem, I'm glad it got resolved. Thanks for your help!

**Comment by DJDavid98** [comment]
One last comment though, `git checkout tags/1.0.8` should probably be just `git checkout 1.0.8`, the former did not work for me.
