### ISSUE TITLE
E_RECOVERABLE_ERROR

### ISSUE THREAD

**Issue by auroraeosrose** [jedisct1/libsodium-php#89]
In PHP E_ERROR is reserved for errors that leave the engine in an unstable state

I understand that the errors in libsodium that bubble up SHOULD and MUST be handled for safety and security reasons - but PHP has an error level for this - E_RECOVERABLE_ERROR

Could we please change the errors from E_ERROR to E_RECOVERABLE_ERROR - this would still mean that a user has to handle the issue

Let's not continue the bad pattern of PHP extensions acting as though they've bombed the engine itself :(

**Comment by jedisct1** [comment]
Done in 770bd4ee45513f858b138951db987bafcc8b23a9

Thanks!

**Comment by auroraeosrose** [comment]
Thank you :)

**Comment by jedisct1** [comment]
Thank *you* for pointing this out!
