### ISSUE TITLE
crypto_aead_chacha20poly1305 producing incorrect tag

### ISSUE THREAD

**Issue by JoeAlamo** [jedisct1/libsodium-php#91]
Hi there,

I believe that the crypto_aead_chacha20poly1305_X functions are producing an incorrect tag. My version major is 9, version minor is 1 and version_string is 1.0.8.

I have ran them against the test vectors in [RFC 7539](https://tools.ietf.org/html/rfc7539#appendix-A.5), and whilst the ciphertext produced is correct the tag is not. I have also ran these test vectors on an [Arduino library ](https://github.com/rweather/arduinolibs/blob/master/libraries/Crypto/ChaChaPoly.cpp) which produce the correct tag ([gist here](https://gist.github.com/JoeAlamo/496f717d118acceb4d6fa15af232fb48)). In both cases, they are using the non-ietf version with the 64bit nonce - which is the one that \Sodium\crypto_aead_chacha20poly1305_{encrypt|decrypt} is calling after looking through the source.

Here is a gist of my test code: [https://gist.github.com/JoeAlamo/b225e7c7736c34424e42f88b63ebb8e4](https://gist.github.com/JoeAlamo/b225e7c7736c34424e42f88b63ebb8e4)

The output can be viewed at [http://joekeilty.co.uk/chachapolytest.php](http://joekeilty.co.uk/chachapolytest.php) for your convenience.

Is there just a dumb mistake I am making here or does there appear to be something wrong?

I appreciate your time.

Cheers.

**Comment by jedisct1** [comment]
`crypto_aead_chacha20poly1305` implements the original construction described [here](https://tools.ietf.org/html/draft-agl-tls-chacha20poly1305-04).

You removed the first 4 bytes of the nonce, so you already noticed the test vector of the RFC didn't work with `crypto_aead_chacha20poly1305()` :)

The IETF variant is also implemented in libsodium, as `crypto_chacha20poly1305_ietf_*` but it looks like the PHP bindings are missing. I will add them as soon as possible.

**Comment by JoeAlamo** [comment]
Hi, thanks for the quick reply :)

Yes that is true, but I have also removed the first 4 bytes using the Arduino library and it produced the correct tag - and it is using the original construction, so that is quite confusing to me.

I will try the test vector from that document linked.

Thank you again.

**Comment by jedisct1** [comment]
The IETF variant [has been added](https://github.com/jedisct1/libsodium-php/commit/63a820a915af64a0617143bb03c7518a61741b14).

Feel free to give it a spin!

**Comment by jedisct1** [comment]
And [your test code](https://gist.github.com/08cd21a4e8a5f49cdc1d15fb4e6214d3) returns [the expected result](https://gist.github.com/ec15f3ccbdd9febf388b2b9643088fbd).

**Comment by JoeAlamo** [comment]
Wow, you sir are a true OG.

I'm going to get this installed and see if I can get my Arduino and PHP box talking to each other.

Will report back shortly.

Thanks!

**Comment by JoeAlamo** [comment]
Hi @jedisct1 ,

That has worked a treat!

Thanks once again for your assistance, it really has been truly invaluable and will greatly help me to complete my dissertation.

**Comment by jedisct1** [comment]
Anytime.

Good luck with your dissertation!
