### ISSUE TITLE
Replace PHP errors with PHP exceptions

### ISSUE THREAD

**Issue by DemiMarie** [jedisct1/libsodium-php#93]
PHP supports exceptions and it is much easier to deal with an exception than an error.

**Comment by soatok** [comment]
:+1: this change could be made along with `\Sodium\*` -> `sodium_*` in the PHP 7.1 RFC branch.

**Comment by drbo** [comment]
I actually like the namespaced version better, but then I am not a regular PHP user.

**Comment by paragonie-scott** [comment]
This is done in #113 :)

**Comment by jedisct1** [comment]
Awesome!
