### ISSUE TITLE
libsodium module times out at system boot

### ISSUE THREAD

**Issue by stevendesu** [jedisct1/libsodium-php#94]
I'm using Ubuntu 16.04 on a VPS hosted by DigitalOcean. After four days I've managed to narrow down my issues to the libsodium-php module

After spinning up a **brand new VPS** (nothing installed except Ubuntu 16.04, no custom hardware config, nothing out of the ordinary) I log into root and run the following set of commands:

```
apt-get install php7.0 php7.0-dev php-pear
apt-get install libsodium-dev
pecl install libsodium
echo "extension=libsodium.so" >> /etc/php/7.0/fpm/php.ini
shutdown -r 0
```

When the server restarts, check on the php7.0-fpm service:

**During startup**

```
root@simple-test:~# service php7.0-fpm status
● php7.0-fpm.service - The PHP 7.0 FastCGI Process Manager
   Loaded: loaded (/lib/systemd/system/php7.0-fpm.service; enabled; vendor preset: enabled)
   Active: activating (start-pre) since Fri 2016-07-29 20:20:42 EDT; 47s ago
  Control: 2287 (php7.0-fpm-chec)
    Tasks: 4
   Memory: 13.0M
      CPU: 46ms
   CGroup: /system.slice/php7.0-fpm.service
           └─control
             ├─2287 /bin/sh /usr/lib/php/php7.0-fpm-checkconf
             ├─2296 /bin/sh /usr/lib/php/php7.0-fpm-checkconf
             ├─2297 /usr/sbin/php-fpm7.0 --fpm-config /etc/php/7.0/fpm/php-fpm.conf -t
             └─2298 grep \[ERROR\]

Jul 29 20:20:42 simple-test systemd[1]: Starting The PHP 7.0 FastCGI Process Manager...
```

**After failure**

```
root@simple-test:~# service php7.0-fpm status
● php7.0-fpm.service - The PHP 7.0 FastCGI Process Manager
   Loaded: loaded (/lib/systemd/system/php7.0-fpm.service; enabled; vendor preset: enabled)
   Active: failed (Result: timeout) since Fri 2016-07-29 20:22:13 EDT; 1min 4s ago
  Process: 2287 ExecStartPre=/usr/lib/php/php7.0-fpm-checkconf (code=killed, signal=TERM)

Jul 29 20:20:42 simple-test systemd[1]: Starting The PHP 7.0 FastCGI Process Manager...
Jul 29 20:22:13 simple-test systemd[1]: php7.0-fpm.service: Start-pre operation timed out. Terminating.
Jul 29 20:22:13 simple-test systemd[1]: Failed to start The PHP 7.0 FastCGI Process Manager.
Jul 29 20:22:13 simple-test systemd[1]: php7.0-fpm.service: Unit entered failed state.
Jul 29 20:22:13 simple-test systemd[1]: php7.0-fpm.service: Failed with result 'timeout'.
```

Note that after it has failed I can manually run `service php7.0-fpm start` and it stats up in milliseconds. This is an issue that **only occurs at boot time**

**Comment by stevendesu** [comment]
Continuing to look into this:

Tracing the startup process, I found that in `/lib/systemd/system/php7.0-fpm.service` it called `/usr/lib/php/php7.0-fpm-checkconf` which gets to the following line before timing out:

```
errors=$(/usr/sbin/php-fpm7.0 --fpm-config "$CONFFILE" -t 2>&1 | grep "\[ERROR\]" || true);
```

Attempting to run `/usr/sbin/php-fpm7.0 --fpm-config "$CONFFILE" -t 2>&1` manually during the first 2-3 minutes after server boot just stalls.

I noticed that if I also put `extension=libsodium.so` into cli/php.ini then for the same first 2-3 minutes after the server boots I can't run `php -v`. It seems like PHP is stalling out in its entirety during this time.

Looking at `libsodium.c` it looks like the `PHP_MINIT_FUNCTION` does nothing but call `sodium_init()`, so I suspect `sodium_init()` is taking 2-3 minutes to complete. Looking at `sodium_init()` in the sodium repo it's calling multiple functions, and I'm not sure how to profile it to see which function is taking so long:

```
    randombytes_stir();
    _sodium_alloc_init();
    _crypto_pwhash_argon2i_pick_best_implementation();
    _crypto_generichash_blake2b_pick_best_implementation();
    _crypto_onetimeauth_poly1305_pick_best_implementation();
    _crypto_scalarmult_curve25519_pick_best_implementation();
    _crypto_stream_chacha20_pick_best_implementation();
```

Since libsodium is a security library, I don't feel safe trying to muck with it and still trust it to be secure, so for all intents and purposes I think it's safe to assume it will **require** 2-3 minutes to start up before we can use PHP. That said, this is preventing php-fpm from loading at system start, forcing me to log into the server and start it manually after a server reboot!

Is it possible for libsodium-php be modified so as to not block when libsodium is uninitialized, and instead throw an exception or an error? The odds of someone accessing a page requiring libsodium-php within the 2 minutes after a server reboot are low enough I could accept the server temporarily throwing a 500 error during this time: but throwing a 502 for hours until I log in to manually run php-fpm is problematic.

**Comment by paragonie-scott** [comment]
First guess: I think the problem is with `randombytes_stir();` and your operating system isn't seeding the kernel's CSPRNG because it's a cloud instance.

**Comment by jedisct1** [comment]
That is very plausible. Now I feel really bad for applications reading `/dev/urandom` and *not* blocking until it is seeded.

Maybe make sure that the service constantly tries to (re)start instead?

Adding
```
Restart=always
````
to the service file should be enough to do it.

**Comment by stevendesu** [comment]
@paragonie-scott A few questions, then:

1. Is there any way to confirm your guess? How could I profile libsodium to see what's taking so long and verify that it's actually `randombytes_stir()`?

2. It's my understanding that as the OS runs, the CSPRNG is constantly being re-seeded with new sources of entropy. Is "stirring" the bytes really necessary, and does it provably increase "randomness" to do so? If there's no new entropy in the system then wouldn't any "stirring" just be stepping forward through the list of pseudo-random numbers?

3. Could libsodium be modified to stir the bits asynchronously, returning SUCCESS on `sodium_init()` almost instantly but blocking on the first attempt to access random bytes until the bytes are finished stirring? The odds of someone hashing a password or encrypting something within the first 3 minutes of server reboot are probably much lower than the odds of someone trying to access static portions of the website (which are similarly waiting for PHP to finish loading)

4. Could a "pseudo-insecure" option be added which stirs the bits asynchronously but allows use of the library before it's finished (meaning for the first couple of minutes the bits aren't "random enough", but after a short while they're fully stirred)... Would this actually be **more** secure since you can't possibly know when someone is going to access random bits, and so there's added entropy from the fact that they could jump in at any point mid-stir?

I'm not a security expert so I'll defer to you if you say 2-3 minutes of stirring is **absolutely mandatory**, I'm just wondering if there's some way the long delay could be mitigated for systems like mine where the CSPRNG isn't seeded at boot time.

**Comment by paragonie-scott** [comment]
> It's my understanding that as the OS runs, the CSPRNG is constantly being re-seeded with new sources of entropy. Is "stirring" the bytes really necessary, and does it provably increase "randomness" to do so?

What's going on here is that `/dev/urandom` will return bytes before it's seeded during system boot. `/dev/random` will not.

So, [libsodium will poll `/dev/random` until it's available to detect that `/dev/urandom` was seeded](https://github.com/jedisct1/libsodium/blob/master/src/libsodium/randombytes/sysrandom/randombytes_sysrandom.c#L116-L142).

The problem here isn't a libsodium bug. The problem here is a fundamental problem with Digital Ocean and Linux that will probably lead to weak cryptography keys being used by DO droplets. For historical precedents:

* https://factorable.net/
* https://certlogik.com/debian-weak-key-check/

**Comment by TheDigitalOrchard** [comment]
Nearly two years later and I'm constantly plagued by this very same issue. I use Ubuntu 16.04 at two different cloud providers (Digital Ocean and Cloud-A), and both are exhibiting this exact same issue with PHP 7.2. I never experienced this startup problem with any past version of PHP.

What is the recommended solution if libsodium embedded into PHP 7.2 is still affecting things in 2018?

**Comment by jedisct1** [comment]
You should complain to these providers for not providing a secure random number source.

And try installing [https://github.com/smuellerDD/jitterentropy-rngd](Jitterentropy).

**Comment by stevendesu** [comment]
@jedisct1 @lfxc I'll do some research into those two daemons. If the sources of entropy come from third-party services then I worry what would happen if those services went down in the future. Would you server just lock up on boot? Would it stop working properly? Would it become less random? I like to minimize dependencies on third-party services when and where possible

**Comment by robAttrell** [comment]
@lfxc I also installed haveged based on your advice, and after trying EVERYTHING I could find online, hours of searching, this worked with *no* other changes. I feel like based on this that haveged was mistakenly assumed to be a mandatory package when you go past php 7.0, but it isn't actually installed with php 7.1+.

I'm not as much a Linux programmer as much as I'm a web administrator who happens to enjoy buggering around in Linux, but somebody who knows more than me should probably file this as an official php 7.1+ bug (and fix).

**Comment by crankycyclops** [comment]
I also just got bit by this since updating a server from 7.1 to 7.2 (I'm also on DigitalOcean.) Like others here, installing the haveged package fixed it for me.

**Comment by mlevarge** [comment]
I second @lxfc and @crankycyclops -- haveged seemed to fix this issue. Awesomesauce!

**Comment by R0Wi** [comment]
I know this is a quite old post now but i had this issue after upgrading from Debian 9 to Debian 10 on my private server. The `apache2` and `php7.3-fpm` services did run into timeouts after reboot, i was only able to run them manually.
`apt-get -y install haveged` fixed the issue, thanks @lfxc

**Comment by paragonie-security** [comment]
@R0Wi Who is your hosting provider?

Haveged doesn't actually fix anything. It just papers over a deep infrastructure deficit.

**Comment by jedisct1** [comment]
https://download.libsodium.org/doc/usage#sodium_init-stalling-on-linux

As @paragonie-security said, `haveged` prevents the process from blocking, but the reason it was blocking is because it wasn't able to gather enough entropy to build a secure random number generator.

Fixing the root cause would be preferable.

**Comment by R0Wi** [comment]
Well i'm hosting the vitual machine myself running kvm on an ubuntu host. I'm just wondering why this occures suddenly after a distro upgrade? Never had that problems before.

**Comment by jedisct1** [comment]
Maybe KVM wasn't configured to enable `virtio-rng`?

Debian has a page about this: https://wiki.debian.org/BoottimeEntropyStarvation

**Comment by jedisct1** [comment]
https://lists.debian.org/debian-devel/2019/02/msg00327.html may explain why that happened after the upgrade.

**Comment by R0Wi** [comment]
@jedisct1 thanks for this information. Indeed i was able to fix the problem by uninstalling `haveged` again and instead configuring `kvm` to provide the random generator of my host machine. You can find a reference [here](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/virtualization_deployment_and_administration_guide/sect-guest_virtual_machine_device_configuration-random_number_generator_device) (i used `/dev/urandom`).

After a reboot i was able to verify everthing is working correctly by applying [these tipp's](https://daniel-lange.com/archives/152-hello-buster.html).

```
root@myhost: # dmesg | grep random
[    0.208088] random: get_random_bytes called from start_kernel+0x93/0x52c with crng_init=0
[    3.102312] random: fast init done
[    3.619668] random: crng init done

root@myhost: # root@myhost: cat /sys/devices/virtual/misc/hw_random/rng_current 
virtio_rng.0
```

Thank you guys !
