### ISSUE TITLE
Sign commits & releases (tags)

### ISSUE THREAD

**Issue by rugk** [jedisct1/libsodium-php#96]
You should consider signing git commits & releases.
- [onionshare#221 (comment)](https://is.gd/7vU4oK)
- It is also displayed on GitHub: https://github.com/blog/2144-gpg-signature-verification
- Here is GitHub's help for this: https://help.github.com/articles/generating-a-gpg-key/
- And here is how you can sign releases: https://wiki.debian.org/Creating%20signed%20GitHub%20releases

**Comment by paragonie-scott** [comment]
:+1: I'm pretty sure Frank knows how to do this, [since he does that for the underlying library already](https://github.com/jedisct1/libsodium/releases/tag/1.0.11), but this is a good idea for future releases.

**Comment by rugk** [comment]
>  I'm pretty sure Frank knows how to do this,

Good, now he just has to use i8t. :smiley: 

> but this is a good idea for future releases.

Not only for releases, also for future commits.
