### ISSUE TITLE
How to check the version number of the PHP extension?

### ISSUE THREAD

**Issue by rugk** [jedisct1/libsodium-php#97]
In the doc you sometimes say:
> Warning: If you're running PHP 7, make sure you're using version 1.0.1 of the PHP extension before using this function.

So how can I check the version of the PHP extension? Using `\Sodium\library_version_major()` and `\Sodium\library_version_minor()`?

**Comment by jedisct1** [comment]
The version is present in the `phpinfo()` output.

Or at runtime:
```php
$ext = new ReflectionExtension('libsodium');
var_dump($ext->getVersion());
```

**Comment by rugk** [comment]
Ah, thanks.
I just discovered that it works with phpversion too:

```php
var_dump(phpversion('libsodium'));
```

I don't know what is better, but at least phpversion also works with PHP 4 according to the PHP doc.

**Comment by Eddcapone** [comment]
Just execute this command in CLI `php -i | grep -i libsodium`
