### ISSUE TITLE
memzero caused php connecion reset

### ISSUE THREAD

**Issue by rugk** [jedisct1/libsodium-php#99]
I encountered a strange case where `memzero` did not throw an error or so, but caused PHPs connection to be "crashed" causing this errors in nginx:
`upstream: "fastcgi://unix:/var/run/php5-fpm[…]:", […] [error] 1433#0: *699 recv() failed (104: Connection reset by peer) while reading response header from upstream,`

For an end user this resulted in server error `503 Bad Gateway`.

Libsodium 1.0.11
PHP 5.6.27-0+deb8u1

```
libsodium

libsodium support => enabled
libsodium compiled version => 1.0.6
libsodium headers version => 1.0.10
libsodium library version => 1.0.11
```

Removed variable is an object. In the past removing the variable worked fine.

So I've tested it with different variables and this is where the error happens:
* Objects
* Booleans
* strings work

**Comment by jedisct1** [comment]
Weird. This is actually not supposed to work on anything but strings:

https://github.com/jedisct1/libsodium-php/blob/master/libsodium.c#L437

**Comment by rugk** [comment]
This is not documented in https://paragonie.com/book/pecl-libsodium/read/03-utilities-helpers.md#memcmp.
However even when a wrong variable is given it should throw an error or so, but not behave like this.

**Comment by jedisct1** [comment]
https://paragonie.com/book/pecl-libsodium/read/03-utilities-helpers.md#memzero

```php
void \Sodium\memzero(&string $secret);
                                        ^^^^^^^
```
